// timing.sdc
// Copyright 2022 Kenta IDA
// Distributed under the Boost Software License, Version 1.0.
//    (See accompanying file LICENSE_1_0.txt or copy at
//          http://www.boost.org/LICENSE_1_0.txt)


create_clock -name clock -period 20.000 -waveform {0 10.000} [get_ports {clock}]
create_clock -name rmii_txclk -period 20.000 -waveform {0 10.000} [get_ports {rmii_txclk}]
# gowin_pll_main_inst/PLLA_inst/CLKOUT0.default_gen_clk is automatically generated by ADVPLL
create_generated_clock -name clock_main -source [get_ports {clock}] -master_clock clock -divide_by 25 -multiply_by 18 [get_nets {main_clock}]
#create_generated_clock -name clock_main -source [get_ports {clock}] -master_clock clock -divide_by 1 -multiply_by 2 [get_nets {main_clock}]

set_clock_groups -asynchronous -group [get_clocks {clock_main}] -group [get_clocks {rmii_txclk}]

set_output_delay -clock rmii_txclk 10 [get_ports {rmii_txen}]
set_output_delay -clock rmii_txclk 10 [get_ports {rmii_txd[0]}]
set_output_delay -clock rmii_txclk 10 [get_ports {rmii_txd[1]}]

report_timing -setup -max_paths 100 -max_common_paths 5
report_timing -setup -rise_from [get_clocks {clock_main}] -to [get_regs {ethernet_video_system_inst/service/protocolHeaderBuffer*}]
report_timing -setup -from [get_regs {ethernet_video_system_inst/service/udpSendContext_destinationAddress*}] -rise_to [get_clocks {clock_main}]