PROJECT_NAME := stop_watch
SRCS := $(wildcard src/*.cst) $(wildcard src/*.sdc) $(wildcard src/*.sv) $(wildcard ../../rtl/segment_led/*.sv) $(wildcard ../../rtl/switch_input/*.sv) project.tcl

include ../build_gowin.mk