set SRC_DIR       [lindex $argv 0]
set RTL_DIR       [lindex $argv 1]
set TARGET        [lindex $argv 2]
set DEVICE_FAMILY [lindex $argv 3]
set DEVICE_PART   [lindex $argv 4]
set PROJECT_NAME  [lindex $argv 5]

set_option -output_base_name ${PROJECT_NAME}
set_device -name $DEVICE_FAMILY $DEVICE_PART

set_option -verilog_std sysv2017
set_option -print_all_synthesis_warning 1
set_option -top_module top
set_option -place_option 1
set_option -route_option 2
set_option -gen_verilog_sim_netlist 1

if {${TARGET} == "tangprimer25k"} {
    set_option -use_cpu_as_gpio 1
    set_option -use_i2c_as_gpio 1
}

set COMMON_DIR [file normalize ${SRC_DIR}/../common]
# Build variants from the environment (see Makefile): CTRL_PULSE=1 (reverse
# channel receiver = PulseResetRx only), TRACE_WIDTH=<bits> (Nano9K demo width)
set defs "// generated by project.tcl\n"
if {[info exists ::env(CTRL_PULSE)] && $::env(CTRL_PULSE) == "1"} { append defs "`define CTRL_PULSE\n" }
# signal map -> TRACE_MAP_WIDTH / TRACE_MAP_HASH (host/tracemap.py). TRACE_MAP=<file>
# selects the map, TRACE_WIDTH=<bits> an anonymous map; default maps/nano9k_demo.map
if {${TARGET} == "tangnano9k_pmod"} {
    set PROJ_DIR [file normalize ${SRC_DIR}/../..]
    if {[info exists ::env(TRACE_WIDTH)]} {
        set mapargs [list --anonymous $::env(TRACE_WIDTH)]
    } elseif {[info exists ::env(TRACE_MAP)]} {
        set mapargs [list [file normalize ${PROJ_DIR}/$::env(TRACE_MAP)]]
    } else {
        set mapargs [list [file normalize ${PROJ_DIR}/maps/nano9k_demo.map]]
    }
    set mapout [exec python3 [file normalize ${PROJ_DIR}/host/tracemap.py] {*}$mapargs --vh trace_map_cfg.vh --rom trace_map_rom.v]
    add_file -type verilog [file normalize trace_map_rom.v]
    puts "tracemap: $mapout"
    set fh [open trace_map_cfg.vh r]; append defs [read $fh]; close $fh
}
# USB=1: host transport over the Pmod USB board (rtl/usb), see top.v
set USB [expr {[info exists ::env(USB)] && $::env(USB) == "1"}]
if {$USB} { append defs "`define USB_HOST\n" }
set RATE [expr {[info exists ::env(RATE)] ? $::env(RATE) : "1G"}]
if {${RATE} == "742M5"} { append defs "`define RATE_742M5\n" }
# 25K-only rate variants (self-test loopback, 8b10b stream): line rate = 50MHz x (MDIV + FRAC/8) / ODIV x 2.
# Columns: MDIV MDIV_FRAC ODIV DELAY_1 FCLK_period_ns pclk_rx_mult pclk_rx_div. 742M5 keeps its own IP dir / PLL / SDC.
array set RATE_TAB {
    1G     {20 0 2 21 2.0    5   2}
    1200M  {24 0 2 18 1.6667 3   1}
    1300M  {26 0 2 16 1.5385 13  4}
    1400M  {28 0 2 15 1.4286 7   2}
    1487M5 {14 7 1 14 1.3445 119 32}
    1600M  {16 0 1 13 1.25   4   1}
}
if {${RATE} != "742M5"} {
    if {![info exists RATE_TAB(${RATE})]} { error "unknown RATE ${RATE} (1G 742M5 1200M 1300M 1400M 1487M5 1600M)" }
    if {${TARGET} != "tangprimer25k" && ${RATE} != "1G"} { error "RATE ${RATE} is a tangprimer25k self-test variant (the Nano9K supports 1G / 742M5)" }
    lassign $RATE_TAB(${RATE}) R_MDIV R_FRAC R_ODIV R_DLY1 R_FPER R_PMUL R_PDIV
    if {[info exists ::env(DELAY1)]} { set R_DLY1 $::env(DELAY1) }
    append defs "`define RATE_MDIV ${R_MDIV}\n`define RATE_MDIV_FRAC ${R_FRAC}\n`define RATE_ODIV ${R_ODIV}\n`define RATE_DELAY1 ${R_DLY1}\n"
}
set fh [open defines_gen.v w]; puts -nonewline $fh $defs; close $fh
add_file -type verilog [file normalize defines_gen.v]
add_file -type verilog [file normalize ${SRC_DIR}/top.v]
add_file -type verilog [file normalize ${RTL_DIR}/trace/tx_link_core.sv]
add_file -type verilog [file normalize ${RTL_DIR}/trace/trace_cdc.sv]
add_file -type verilog [file normalize ${RTL_DIR}/trace/trace_afifo.sv]
add_file -type verilog [file normalize ${RTL_DIR}/trace/trace_frontend.sv]
add_file -type verilog [file normalize ${RTL_DIR}/trace/trace_link_tx.sv]
add_file -type verilog [file normalize ${RTL_DIR}/trace/easycdr_trace_tx.sv]
add_file -type verilog [file normalize ${RTL_DIR}/displayport/src/encoder_8b10b.sv]

# Reverse control channel (rtl/manchester, Veryl output - run `veryl build`
# in rtl/manchester after editing the .veryl sources)
if {${TARGET} == "tangprimer25k"} {
    add_file -type verilog [file normalize ${RTL_DIR}/manchester/manchester_tx.sv]
    add_file -type verilog [file normalize ${RTL_DIR}/manchester/pulse_reset_tx.sv]
} else {
    add_file -type verilog [file normalize ${RTL_DIR}/manchester/pulse_reset_rx.sv]
    add_file -type verilog [file normalize ${RTL_DIR}/manchester/manchester_rx.sv]
    add_file -type verilog [file normalize ${RTL_DIR}/manchester/ctrl_frame_rx.sv]
    add_file -type verilog [file normalize ${RTL_DIR}/manchester/trace_ctrl_regs.sv]
}

if {${TARGET} == "tangprimer25k"} {
    # host side: EasyCDR RX + capture buffer + UART dump
    add_file -type verilog [file normalize ${RTL_DIR}/trace/trace_capture.sv]
    add_file -type verilog [file normalize ${RTL_DIR}/trace/trace_rx_decoder.sv]
    add_file -type verilog [file normalize ${RTL_DIR}/trace/trace_link_diag.sv]
    add_file -type verilog [file normalize ${RTL_DIR}/trace/trace_sym_inject.sv]
    # self-test transmitter's signal-map text ROM
    set PROJ_DIR [file normalize ${SRC_DIR}/../..]
    exec python3 [file normalize ${PROJ_DIR}/host/tracemap.py] [file normalize ${PROJ_DIR}/maps/primer25k_selftest.map] --rom trace_map_rom_selftest.v --module trace_map_rom_selftest
    add_file -type verilog [file normalize trace_map_rom_selftest.v]
    add_file -type verilog [file normalize ${RTL_DIR}/uart/uart_tx.sv]
    add_file -type verilog [file normalize ${RTL_DIR}/uart/uart_rx.sv]
    if {$USB} {
        # USB 2.0 HS device core + Gowin PHY front end (rtl/usb, Veryl output) and its PLLs (eda/usb_device)
        set USB_SRC [file normalize ${SRC_DIR}/../../../usb_device/src/tangprimer25k]
        foreach f {usb_pkg usb_phy_rx usb_phy_tx usb_phy usb_sie usb_descriptor_rom usb_device} {
            add_file -type verilog [file normalize ${RTL_DIR}/usb/${f}.sv]
        }
        add_file -type verilog [file normalize ${RTL_DIR}/usb/gowin/usb_phy_gowin.v]
        add_file -type verilog [file normalize ${RTL_DIR}/usb/gowin/usb_hs_cdr.v]
        add_file -type verilog [file normalize ${RTL_DIR}/usb/gowin/usb_hs_os32.v]
        add_file -type verilog [file normalize ${RTL_DIR}/oscdr/os_cdr.sv]
        add_file -type verilog [file normalize ${RTL_DIR}/oscdr/bit_gearbox.sv]
        add_file -type verilog [file normalize ${USB_SRC}/pll_usb/pll_usb.v]
        add_file -type verilog [file normalize ${USB_SRC}/pll_usb_os/pll_usb_os.v]
    } else {
        add_file -type verilog [file normalize ${SRC_DIR}/pll_tx_500m/pll_tx_500m.v]
    }

    # EasyCDR IP: 10bit + Word Alignment + 8B/10B Decoding (K28.5). The IP
    # directory (sampling delay taps) and the RX PLL follow the link rate.
    if {${RATE} == "742M5"} {
        set IP_DIR ${SRC_DIR}/easycdr_1912_742m5
        add_file -type verilog [file normalize ${SRC_DIR}/pll_rx_371m_4ph/pll_rx_371m_4ph.v]
    } else {
        set IP_DIR ${SRC_DIR}/easycdr_1912
        add_file -type verilog [file normalize ${SRC_DIR}/pll_rx_500m_4ph/pll_rx_500m_4ph.v]
    }
    set_option -include_path [file normalize ${IP_DIR}]
    add_file -type verilog [file normalize ${IP_DIR}/EasyCDR_Top.v]
    add_file -type verilog [file normalize ${IP_DIR}/EasyCDR.v]
}

if {${TARGET} == "tangnano9k_pmod"} {
    # TX-only trace source: 999Mbps (default) or 742.5Mbps from the 27MHz crystal
    if {${RATE} == "742M5"} {
        add_file -type verilog [file normalize ${SRC_DIR}/pll_tx_3712/pll_tx_3712.v]
    } else {
        add_file -type verilog [file normalize ${SRC_DIR}/pll_tx_4995/pll_tx_4995.v]
    }
}

if {$USB} {
    add_file -type cst [file normalize ${SRC_DIR}/pins_usb.cst]
} else {
    add_file -type cst [file normalize ${SRC_DIR}/pins.cst]
}
if {${RATE} == "742M5"} {
    add_file -type sdc [file normalize ${SRC_DIR}/timing_742m5.sdc]
} elseif {${TARGET} == "tangprimer25k"} {
    # timing.sdc is a template (@FP@/@FH@ FCLK period, @PM@/@PD@ pclk_rx from 50MHz)
    set fh [open ${SRC_DIR}/timing.sdc r]; set sdc [read $fh]; close $fh
    set sdc [string map [list @FP@ ${R_FPER} @FH@ [expr {${R_FPER} / 2.0}] @PM@ ${R_PMUL} @PD@ ${R_PDIV}] $sdc]
    if {$USB} { set fh [open ${SRC_DIR}/timing_usb.sdc r]; append sdc "\n" [read $fh]; close $fh }
    set fh [open timing_gen.sdc w]; puts -nonewline $fh $sdc; close $fh
    add_file -type sdc [file normalize timing_gen.sdc]
} else {
    add_file -type sdc [file normalize ${SRC_DIR}/timing.sdc]
}

run all
