set SRC_DIR       [lindex $argv 0]
set RTL_DIR       [lindex $argv 1]
set TARGET        [lindex $argv 2]
set DEVICE_FAMILY [lindex $argv 3]
set DEVICE_PART   [lindex $argv 4]
set PROJECT_NAME  [lindex $argv 5]

set_option -output_base_name ${PROJECT_NAME}
set_device -name $DEVICE_FAMILY $DEVICE_PART

set_option -verilog_std sysv2017
set_option -print_all_synthesis_warning 1
set_option -top_module top
set_option -place_option 1
set_option -route_option 2
set_option -gen_verilog_sim_netlist 1

if {${TARGET} == "tangprimer25k"} {
    set_option -use_cpu_as_gpio 1
    set_option -use_i2c_as_gpio 1
}

set COMMON_DIR [file normalize ${SRC_DIR}/../common]
# Build variants from the environment (see Makefile): CTRL_PULSE=1 (reverse
# channel receiver = PulseResetRx only), TRACE_WIDTH=<bits> (Nano9K demo width)
set defs "// generated by project.tcl\n"
if {[info exists ::env(CTRL_PULSE)] && $::env(CTRL_PULSE) == "1"} { append defs "`define CTRL_PULSE\n" }
# signal map -> TRACE_MAP_WIDTH / TRACE_MAP_HASH (host/tracemap.py). TRACE_MAP=<file>
# selects the map, TRACE_WIDTH=<bits> an anonymous map; default maps/nano9k_demo.map
if {${TARGET} == "tangnano9k_pmod"} {
    set PROJ_DIR [file normalize ${SRC_DIR}/../..]
    if {[info exists ::env(TRACE_WIDTH)]} {
        set mapargs [list --anonymous $::env(TRACE_WIDTH)]
    } elseif {[info exists ::env(TRACE_MAP)]} {
        set mapargs [list [file normalize ${PROJ_DIR}/$::env(TRACE_MAP)]]
    } else {
        set mapargs [list [file normalize ${PROJ_DIR}/maps/nano9k_demo.map]]
    }
    set mapout [exec python3 [file normalize ${PROJ_DIR}/host/tracemap.py] {*}$mapargs --vh trace_map_cfg.vh --rom trace_map_rom.v]
    add_file -type verilog [file normalize trace_map_rom.v]
    puts "tracemap: $mapout"
    set fh [open trace_map_cfg.vh r]; append defs [read $fh]; close $fh
}
set RATE [expr {[info exists ::env(RATE)] ? $::env(RATE) : "1G"}]
if {${RATE} == "742M5"} { append defs "`define RATE_742M5\n" }
set fh [open defines_gen.v w]; puts -nonewline $fh $defs; close $fh
add_file -type verilog [file normalize defines_gen.v]
add_file -type verilog [file normalize ${SRC_DIR}/top.v]
add_file -type verilog [file normalize ${RTL_DIR}/trace/tx_link_core.sv]
add_file -type verilog [file normalize ${COMMON_DIR}/trace_cdc.v]
add_file -type verilog [file normalize ${COMMON_DIR}/trace_afifo.v]
add_file -type verilog [file normalize ${RTL_DIR}/trace/trace_frontend.sv]
add_file -type verilog [file normalize ${RTL_DIR}/trace/trace_link_tx.sv]
add_file -type verilog [file normalize ${COMMON_DIR}/easycdr_trace_tx.v]
add_file -type verilog [file normalize ${RTL_DIR}/displayport/src/encoder_8b10b.sv]

# Reverse control channel (rtl/manchester, Veryl output - run `veryl build`
# in rtl/manchester after editing the .veryl sources)
if {${TARGET} == "tangprimer25k"} {
    add_file -type verilog [file normalize ${RTL_DIR}/manchester/manchester_tx.sv]
    add_file -type verilog [file normalize ${RTL_DIR}/manchester/pulse_reset_tx.sv]
} else {
    add_file -type verilog [file normalize ${RTL_DIR}/manchester/pulse_reset_rx.sv]
    add_file -type verilog [file normalize ${RTL_DIR}/manchester/manchester_rx.sv]
    add_file -type verilog [file normalize ${RTL_DIR}/manchester/ctrl_frame_rx.sv]
    add_file -type verilog [file normalize ${RTL_DIR}/manchester/trace_ctrl_regs.sv]
}

if {${TARGET} == "tangprimer25k"} {
    # host side: EasyCDR RX + capture buffer + UART dump
    add_file -type verilog [file normalize ${SRC_DIR}/trace_capture.v]
    add_file -type verilog [file normalize ${SRC_DIR}/trace_rx_decoder.v]
    add_file -type verilog [file normalize ${SRC_DIR}/trace_link_diag.v]
    add_file -type verilog [file normalize ${SRC_DIR}/trace_sym_inject.v]
    # self-test transmitter's signal-map text ROM
    set PROJ_DIR [file normalize ${SRC_DIR}/../..]
    exec python3 [file normalize ${PROJ_DIR}/host/tracemap.py] [file normalize ${PROJ_DIR}/maps/primer25k_selftest.map] --rom trace_map_rom_selftest.v --module trace_map_rom_selftest
    add_file -type verilog [file normalize trace_map_rom_selftest.v]
    add_file -type verilog [file normalize ${RTL_DIR}/uart/uart_tx.sv]
    add_file -type verilog [file normalize ${RTL_DIR}/uart/uart_rx.sv]
    add_file -type verilog [file normalize ${SRC_DIR}/pll_tx_500m/pll_tx_500m.v]

    # EasyCDR IP: 10bit + Word Alignment + 8B/10B Decoding (K28.5). The IP
    # directory (sampling delay taps) and the RX PLL follow the link rate.
    if {${RATE} == "742M5"} {
        set IP_DIR ${SRC_DIR}/easycdr_1912_742m5
        add_file -type verilog [file normalize ${SRC_DIR}/pll_rx_371m_4ph/pll_rx_371m_4ph.v]
    } else {
        set IP_DIR ${SRC_DIR}/easycdr_1912
        add_file -type verilog [file normalize ${SRC_DIR}/pll_rx_500m_4ph/pll_rx_500m_4ph.v]
    }
    set_option -include_path [file normalize ${IP_DIR}]
    add_file -type verilog [file normalize ${IP_DIR}/EasyCDR_Top.v]
    add_file -type verilog [file normalize ${IP_DIR}/EasyCDR.v]
}

if {${TARGET} == "tangnano9k_pmod"} {
    # TX-only trace source: 999Mbps (default) or 742.5Mbps from the 27MHz crystal
    if {${RATE} == "742M5"} {
        add_file -type verilog [file normalize ${SRC_DIR}/pll_tx_3712/pll_tx_3712.v]
    } else {
        add_file -type verilog [file normalize ${SRC_DIR}/pll_tx_4995/pll_tx_4995.v]
    }
}

add_file -type cst [file normalize ${SRC_DIR}/pins.cst]
if {${RATE} == "742M5"} {
    add_file -type sdc [file normalize ${SRC_DIR}/timing_742m5.sdc]
} else {
    add_file -type sdc [file normalize ${SRC_DIR}/timing.sdc]
}

run all
