[project]
name    = "nvme"
version = "0.1.0"

[build]
clock_type          = "posedge"
reset_type          = "sync_high"
omit_project_prefix = true

[test]
include_files = [
    "test/nvme_core_test_body.sv",
    "test/nvme_controller_test_body.sv",
    "test/nvme_tcp_target_test_body.sv",
]

[test.verilator]
compile_args = [
    "nvme_core_test_body.sv",
    "nvme_controller_test_body.sv",
    "nvme_tcp_target_test_body.sv",
    "-Wno-WIDTHEXPAND",
    "-Wno-WIDTHTRUNC",
    "-Wno-CASEINCOMPLETE",
    "-Wno-UNUSEDSIGNAL",
    "-Wno-UNDRIVEN",
    "-Wno-PINMISSING",
    "-Wno-INITIALDLY",
    "-Wno-TIMESCALEMOD",
    "-Wno-UNUSEDPARAM",
]
