// generated by tracemap.py: trace_map_rom, 24 bytes
module trace_map_rom(input wire [7:0] addr, output reg [7:0] data, output wire [7:0] len);
    assign len = 8'd24;
    always @(*) begin
        case (addr)
        8'd0: data = 8'h63;
        8'd1: data = 8'h6f;
        8'd2: data = 8'h75;
        8'd3: data = 8'h6e;
        8'd4: data = 8'h74;
        8'd5: data = 8'h3a;
        8'd6: data = 8'h38;
        8'd7: data = 8'h3a;
        8'd8: data = 8'h64;
        8'd9: data = 8'h65;
        8'd10: data = 8'h63;
        8'd11: data = 8'h0a;
        8'd12: data = 8'h73;
        8'd13: data = 8'h32;
        8'd14: data = 8'h3a;
        8'd15: data = 8'h31;
        8'd16: data = 8'h0a;
        8'd17: data = 8'h73;
        8'd18: data = 8'h70;
        8'd19: data = 8'h61;
        8'd20: data = 8'h72;
        8'd21: data = 8'h65;
        8'd22: data = 8'h3a;
        8'd23: data = 8'h37;
        default: data = 8'h00;
        endcase
    end
endmodule
