#!/usr/bin/env python3
"""Trace signal map: parse, canonicalise, hash, and emit build/host artefacts.

  tracemap.py MAP.map                       print the parsed map, width and hash
  tracemap.py MAP.map --vh out.vh           Verilog `define TRACE_MAP_WIDTH / TRACE_MAP_HASH
  tracemap.py --anonymous N --vh out.vh     unnamed map bit0..bit(N-1)
  tracemap.py MAP.map --json out.json       for host tools

Map syntax: entries "name[:width[:radix]]" separated by newlines or commas,
'#' comments. Width defaults to 1, radix to hex (hex|dec|bin). Bits are
assigned LSB first. The hash is CRC-32 (zlib) of the canonical string
"name:width,name:width,..." (radix excluded), so any change of names, widths
or order changes the hash. The same function is implemented in the browser
viewer (index.html) and must stay identical.
"""
import argparse, json, re, sys, zlib

def parse(text):
    sigs = []
    entries = []
    for line in text.splitlines():
        entries += re.split(r",(?![^()]*\))", line.split("#", 1)[0])   # strip comments, split on commas outside enum(...)
    for raw in entries:
        s = raw.strip()
        if not s: continue
        parts = s.split(":")
        name = parts[0].strip()
        if not re.match(r"^[A-Za-z_][A-Za-z0-9_]*$", name): raise ValueError(f"bad signal name: {name!r}")
        width = int(parts[1]) if len(parts) > 1 and parts[1].strip() else 1
        radix = ":".join(parts[2:]).strip() if len(parts) > 2 else "hex"
        names = None
        m = re.match(r"^enum\s*\((.*)\)$", radix, re.I)
        if m: names = [n for n in re.split(r"[,\s]+", m.group(1)) if n]; radix = "enum"
        else: radix = radix.lower()
        if radix not in ("hex", "dec", "bin", "enum"): raise ValueError(f"bad radix for {name}: {radix}")
        if width < 1 or width > 64: raise ValueError(f"bad width for {name}: {width}")
        sigs.append({"name": name, "width": width, "radix": radix, "names": names})
    lo = 0
    for s in sigs: s["lsb"] = lo; lo += s["width"]
    return sigs, lo

def canonical(sigs): return ",".join(f"{s['name']}:{s['width']}" for s in sigs)
def display(sigs):
    """text distributed by the transmitter (newline separated, same syntax as the map file)"""
    out = []
    for s in sigs:
        r = "" if s["radix"] == "hex" else (":enum(" + ",".join(s["names"]) + ")" if s["radix"] == "enum" else ":" + s["radix"])
        out.append(f"{s['name']}:{s['width']}{r}")
    return "\n".join(out)
def rom_verilog(sigs, module="trace_map_rom"):
    text = display(sigs).encode()
    if len(text) > 255: raise SystemExit(f"map text is {len(text)} bytes, maximum 255")
    lines = [f"// generated by tracemap.py: {module}, {len(text)} bytes", f"module {module}(input wire [7:0] addr, output reg [7:0] data, output wire [7:0] len);",
             f"    assign len = 8'd{len(text)};", "    always @(*) begin", "        case (addr)"]
    lines += [f"        8'd{i}: data = 8'h{b:02x};" for i, b in enumerate(text)]
    lines += ["        default: data = 8'h00;", "        endcase", "    end", "endmodule", ""]
    return "\n".join(lines)
def crc32(sigs): return zlib.crc32(canonical(sigs).encode()) & 0xffffffff
def anonymous(n): return [{"name": f"bit{i}", "width": 1, "radix": "bin", "lsb": i} for i in range(n)], n

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("map", nargs="?")
    ap.add_argument("--anonymous", type=int, help="unnamed map of N bits")
    ap.add_argument("--vh"); ap.add_argument("--json")
    ap.add_argument("--rom", help="write a Verilog byte-ROM module holding the map text (transmitter side)")
    ap.add_argument("--module", default="trace_map_rom", help="ROM module name")
    ap.add_argument("--display", action="store_true", help="print the distributed text form")
    a = ap.parse_args()
    if a.anonymous: sigs, width = anonymous(a.anonymous); src = f"anonymous {a.anonymous}"
    elif a.map: sigs, width = parse(open(a.map).read()); src = a.map
    else: ap.error("map file or --anonymous required")
    if width % 8: sys.exit(f"total width {width} is not a multiple of 8")
    h = crc32(sigs)
    if a.vh:
        with open(a.vh, "w") as f:
            f.write(f"// generated by tracemap.py from {src}: {canonical(sigs)}\n")
            f.write(f"`define TRACE_MAP_WIDTH {width}\n`define TRACE_MAP_HASH 32'h{h:08x}\n")
    if a.rom:
        open(a.rom, "w").write(rom_verilog([] if a.anonymous else sigs, a.module))   # anonymous: empty (LEN 0)
    if a.display:
        print(display(sigs)); return
    if a.json:
        json.dump({"source": src, "width": width, "hash": f"{h:08x}", "signals": sigs}, open(a.json, "w"), indent=1)
    print(f"{src}: WIDTH={width} HASH=0x{h:08x}")
    for s in sigs: print(f"  {s['name']:<12} [{s['lsb']+s['width']-1}:{s['lsb']}] {s['radix']}")

if __name__ == "__main__":
    main()
