#!/usr/bin/env python3
"""Generates usb_descriptor_rom.veryl (descriptor ROM + usb_desc_pkg offsets).

Descriptors: device (bcdUSB 2.10 so that hosts ask for the BOS), configuration (FS / HS,
the HS one doubles as OTHER_SPEED), device qualifier, strings, the BOS with the Microsoft
OS 2.0 platform capability, and the MS OS 2.0 descriptor set (Compatible ID "WINUSB":
Windows then binds WinUSB automatically, which WebUSB in Chrome needs). The set is served
by the vendor request bRequest = MS_VENDOR_CODE, wIndex = 7 (usb_device.veryl).
"""
import sys

MS_VENDOR_CODE = 0x20

def le16(x): return [x & 0xff, x >> 8]
def string_desc(s):
    b = s.encode("utf-16-le"); return [2 + len(b), 0x03] + list(b)

dev = [0x12, 0x01] + le16(0x0210) + [0xFF, 0x00, 0x00, 0x40, "VID_L", "VID_H", "PID_L", "PID_H"] + le16(0x0100) + [0x01, 0x02, 0x03, 0x01]
def config(mps):
    return ([0x09, 0x02] + le16(32) + [0x01, 0x01, 0x00, 0x80, 0x32] +
            [0x09, 0x04, 0x00, 0x00, 0x02, 0xFF, 0x00, 0x00, 0x00] +
            [0x07, 0x05, 0x01, 0x02] + le16(mps) + [0x00] +
            [0x07, 0x05, 0x81, 0x02] + le16(mps) + [0x00])
qual = [0x0A, 0x06] + le16(0x0210) + [0xFF, 0x00, 0x00, 0x40, 0x01, 0x00]
str0 = [0x04, 0x03, 0x09, 0x04]
str1 = string_desc("fpga_samples")
str2 = string_desc("USB PHY Sample")
str3 = string_desc("000001")
# MS OS 2.0 descriptor set: header + Compatible ID feature descriptor
msos = ([0x0A, 0x00, 0x00, 0x00, 0x00, 0x00, 0x03, 0x06] + le16(10 + 20) +
        [0x14, 0x00, 0x03, 0x00] + list(b"WINUSB\0\0") + [0] * 8)
uuid = [0xDF, 0x60, 0xDD, 0xD8, 0x89, 0x45, 0xC7, 0x4C, 0x9C, 0xD2, 0x65, 0x9D, 0x9E, 0x64, 0x8A, 0x9F]  # {D8DD60DF-4589-4CC7-9CD2-659D9E648A9F}
cap_msos = [0x1C, 0x10, 0x05, 0x00] + uuid + [0x00, 0x00, 0x03, 0x06] + le16(len(msos)) + [MS_VENDOR_CODE, 0x00]
bos = [0x05, 0x0F] + le16(5 + len(cap_msos)) + [0x01] + cap_msos

table = [("DEV", dev), ("CFG_FS", config(64)), ("CFG_HS", config(512)), ("QUAL", qual),
         ("STR0", str0), ("STR1", str1), ("STR2", str2), ("STR3", str3), ("BOS", bos), ("MSOS", msos)]

out = []
out.append("""// SPDX-License-Identifier: BSL-1.0
// Copyright Kenta Ida 2026.
// Distributed under the Boost Software License, Version 1.0.
//    (See accompanying file LICENSE_1_0.txt or copy at
//          https://www.boost.org/LICENSE_1_0.txt)
/**
 * @file usb_descriptor_rom.veryl
 * @brief Descriptor ROM for the sample USB device (generated by gen_descriptor_rom.py,
 *        do not edit by hand).
 *
 * A single byte-addressed combinational ROM holding, in order:""")
addr = 0; offs = {}
for name, d in table:
    out.append(f" *   {name:7s} @{addr:3d} len {len(d)}"); offs[name] = (addr, len(d)); addr += len(d)
assert addr <= 256, addr
out.append(f""" *
 * Device: vendor-specific class (0xFF), bcdUSB 2.10, bMaxPacketSize0 = 64, one
 * configuration with one interface and two bulk endpoints (EP1 OUT /
 * EP1 IN, 64 bytes FS / 512 bytes HS). The HS variant of the
 * configuration doubles as the OTHER_SPEED_CONFIGURATION (the device
 * core patches bDescriptorType to 0x07 when serving it). BOS carries the
 * Microsoft OS 2.0 platform capability (vendor code 0x{MS_VENDOR_CODE:02X}); the MS OS 2.0
 * descriptor set (Compatible ID WINUSB) is served by that vendor request with
 * wIndex = 7. Vendor / product IDs come from the parameters.
 */
pub package usb_desc_pkg {{""")
for name, (a, n) in offs.items():
    out.append(f"    const {name}_ADDR: logic<8> = 8'd{a};")
    out.append(f"    const {name}_LEN : logic<8> = 8'd{n};")
out.append(f"    const MS_VENDOR_CODE: logic<8> = 8'h{MS_VENDOR_CODE:02X};")
out.append("""}

pub module UsbDescriptorRom #(
    param VENDOR_ID : logic<16> = 16'h1209,
    param PRODUCT_ID: logic<16> = 16'h0001,
) (
    i_addr: input  logic<8>,
    o_data: output logic<8>,
) {
    always_comb {
        case i_addr {""")
sym = {"VID_L": "VENDOR_ID[7:0]", "VID_H": "VENDOR_ID[15:8]", "PID_L": "PRODUCT_ID[7:0]", "PID_H": "PRODUCT_ID[15:8]"}
i = 0
for name, d in table:
    for b in d:
        v = sym[b] if isinstance(b, str) else f"8'h{b:02X}"
        out.append(f"            8'd{i}: o_data = {v};"); i += 1
out.append("""            default: o_data = 8'h00;
        }
    }
}
""")
open(sys.argv[1] if len(sys.argv) > 1 else "usb_descriptor_rom.veryl", "w").write("\n".join(out))
print(f"{i} bytes: " + ", ".join(f"{k}@{a}+{n}" for k, (a, n) in offs.items()))
