[project]
name    = "usb"
version = "0.1.0"

[build]
clock_type          = "posedge"
reset_type          = "sync_high"
omit_project_prefix = true

[test]
include_files = [
    "test/usb_host_bfm.sv",
    "test/usb_phy_loopback_body.sv",
    "test/usb_device_test_body.sv",
]

[test.verilator]
compile_args = [
    "usb_host_bfm.sv",
    "usb_phy_loopback_body.sv",
    "usb_device_test_body.sv",
    "-Wno-WIDTHEXPAND",
    "-Wno-WIDTHTRUNC",
    "-Wno-CASEINCOMPLETE",
    "-Wno-UNUSEDSIGNAL",
    "-Wno-UNDRIVEN",
    "-Wno-PINMISSING",
    "-Wno-INITIALDLY",
    "-Wno-TIMESCALEMOD",
    "-Wno-UNUSEDPARAM",
]
