#!/usr/bin/env python3
# SPDX-License-Identifier: BSL-1.0
# Copyright Kenta Ida 2026.
# Distributed under the Boost Software License, Version 1.0.
#    (See accompanying file LICENSE_1_0.txt or copy at
#          https://www.boost.org/LICENSE_1_0.txt)
"""Write lut_init_rom.sv: the colour tables' power-on contents for
crop_to_hub75 (make GAMMA=<g>), out = in^g rounded to `bits` displayed
bits - the same values as `loopctl.py gamma <g> rgb <bits>`.

  python3 gen_lut_init.py --gamma 2.2 [--bits 6] [--out lut_init_rom.sv]
"""
import argparse


def table(g, bits):
    top = (1 << bits) - 1
    return [round(((i / 255.0) ** g) * top) << (8 - bits) for i in range(256)]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--gamma", type=float, required=True)
    ap.add_argument("--bits", type=int, default=6)
    ap.add_argument("--out", default="lut_init_rom.sv")
    a = ap.parse_args()
    t = table(a.gamma, a.bits)
    lines = [
        "// generated by gen_lut_init.py - do not edit\n",
        f"// colour table power-on contents: gamma {a.gamma}, {a.bits} displayed bits\n",
        "module lut_init_rom (\n",
        "    input  wire  [7:0] i_addr,\n",
        "    output logic [7:0] o_data\n",
        ");\n",
        "    always_comb begin\n",
        "        case (i_addr)\n",
    ]
    lines += [f"            8'h{i:02X}: o_data = 8'h{v:02X};\n" for i, v in enumerate(t)]
    lines += [
        "            default: o_data = 8'h00;\n",
        "        endcase\n",
        "    end\n",
        "endmodule\n",
    ]
    with open(a.out, "w") as f:
        f.writelines(lines)


if __name__ == "__main__":
    main()
