set SRC_DIR       [lindex $argv 0]
set RTL_DIR       [lindex $argv 1]
set TARGET        [lindex $argv 2]
set DEVICE_FAMILY [lindex $argv 3]
set DEVICE_PART   [lindex $argv 4]
set PROJECT_NAME  [lindex $argv 5]

set_option -output_base_name ${PROJECT_NAME}
set_device -name $DEVICE_FAMILY $DEVICE_PART

set_option -verilog_std sysv2017
set_option -print_all_synthesis_warning 1
set_option -top_module top

if {${TARGET} == "tangprimer25k"} {
    set_option -use_cpu_as_gpio 1
    # B2 / C2 (status outputs, 40-pin header 14 / 13) are dual-purpose pins.
    set_option -use_i2c_as_gpio 1
    set_option -use_done_as_gpio 1
    set_option -use_ready_as_gpio 1
    set_option -use_sspi_as_gpio 1
}

# Panel configuration from the environment: PANEL = <W>x<H>, W / H = 64 or
# 128 (default 128x128).
set PANEL [expr {[info exists ::env(PANEL)] && $::env(PANEL) ne "" ? $::env(PANEL) : "128x128"}]
regexp {^([0-9]+)x([0-9]+)$} ${PANEL} -> DISP_W DISP_H
set fh [open defines_gen.v w]
puts $fh "// generated by project.tcl"
puts $fh "`define DISP_W ${DISP_W}"
puts $fh "`define DISP_H ${DISP_H}"
# BITS = BCM bit planes per colour (default 5), HUB75_CLKDIV = shift-clock
# divider (default 1: 12.5 MHz; 0: 25 MHz)
if {[info exists ::env(BITS)] && $::env(BITS) ne ""} { puts $fh "`define COMPONENT_BITS $::env(BITS)" }
if {[info exists ::env(HUB75_CLKDIV)] && $::env(HUB75_CLKDIV) ne ""} { puts $fh "`define HUB75_CLKDIV $::env(HUB75_CLKDIV)" }
close $fh
add_file -type verilog [file normalize defines_gen.v]

set CAPTURE_DIR [file normalize ${SRC_DIR}/../../../dvi_capture/src/${TARGET}]
set LOOP_DIR    [file normalize ${SRC_DIR}/../../../dvi_loopback/src/${TARGET}]

# --- Veryl-generated cores ---
add_file -type verilog [file normalize ${RTL_DIR}/dvi_in/dvi_in.sv]
add_file -type verilog [file normalize ${RTL_DIR}/hub75/hub75.sv]
add_file -type verilog [file normalize ${RTL_DIR}/ddc_edid/ddc_edid.sv]
add_file -type verilog [file normalize ${RTL_DIR}/ddc_edid/edid_rom.sv]
add_file -type verilog [file normalize ${RTL_DIR}/ddc_edid/edid_rom_1080p.sv]
add_file -type verilog [file normalize ${RTL_DIR}/uart/uart_tx.sv]
add_file -type verilog [file normalize ${RTL_DIR}/uart/uart_rx.sv]

# --- DVI RX PHY, PLL and reset shared with eda/dvi_capture ---
add_file -type verilog ${CAPTURE_DIR}/iser10_lane.sv
add_file -type verilog ${CAPTURE_DIR}/dvi_in_phy.sv
add_file -type verilog ${CAPTURE_DIR}/reset_seq.sv
add_file -type verilog ${CAPTURE_DIR}/ip/gowin_pll_dvi/gowin_pll_dvi.v

# --- Diagnostics shared with eda/dvi_loopback ---
add_file -type verilog ${LOOP_DIR}/frame_sum.sv
add_file -type verilog ${LOOP_DIR}/loop_check.sv
add_file -type verilog ${LOOP_DIR}/loop_report.sv

# --- Crop / CDC / top ---
add_file -type verilog [file normalize ${SRC_DIR}/crop_to_hub75.sv]
add_file -type verilog [file normalize ${SRC_DIR}/async_fifo.sv]
add_file -type verilog [file normalize ${SRC_DIR}/top.sv]

add_file -type cst [file normalize ${SRC_DIR}/pins.cst]
add_file -type sdc [file normalize ${SRC_DIR}/timing.sdc]

run all
