[project]
name = "axi4s"
version = "0.1.0"
authors = ["Kenta IDA <fuga@fugafuga.org>"]
license = "BSL-1.0"

[build]
clock_type = "posedge"
reset_type = "sync_low"
target = { type = "source" }

[dependencies]
