set SRC_DIR       [lindex $argv 0]
set RTL_DIR       [lindex $argv 1]
set TARGET        [lindex $argv 2]
set DEVICE_FAMILY [lindex $argv 3]
set DEVICE_PART   [lindex $argv 4]
set PROJECT_NAME  [lindex $argv 5]

set_option -output_base_name ${PROJECT_NAME}
set_option -verilog_std sysv2017
set_option -print_all_synthesis_warning 1
set_option -top_module top
set_option -place_option 1
set_option -route_option 2
set_option -gen_verilog_sim_netlist 1
set_device -name $DEVICE_FAMILY $DEVICE_PART
if {${TARGET} == "tangprimer25k"} {
    set_option -use_cpu_as_gpio 1
    set_option -use_i2c_as_gpio 1
}

# Build variants from the environment: USE_EASYCDR_IP=1 (Gowin-IP receiver),
# DYN_DLY1=1 (OSIDES32 IODELAY_1 in dynamic mode, experiment)
set USE_IP [expr {[info exists ::env(USE_EASYCDR_IP)] && $::env(USE_EASYCDR_IP) == "1"}]
set defs "// generated by project.tcl\n"
if {${USE_IP}} { append defs "`define USE_EASYCDR_IP\n" }
if {[info exists ::env(DYN_DLY1)] && $::env(DYN_DLY1) == "1"} { append defs "`define DYN_DLY1\n" }
if {[info exists ::env(DYN_DLY0)] && $::env(DYN_DLY0) == "1"} { append defs "`define DYN_DLY0\n" }
if {[info exists ::env(ADAPT_DLY1)] && $::env(ADAPT_DLY1) == "1"} { append defs "`define ADAPT_DLY1\n" }
if {[info exists ::env(IODLY_TEST)] && $::env(IODLY_TEST) == "1"} { append defs "`define IODLY_TEST\n" }
if {[info exists ::env(IODLY_DYN)] && $::env(IODLY_DYN) == "1"} { append defs "`define IODLY_DYN\n" }
if {[info exists ::env(IODLY_ADAPT)] && $::env(IODLY_ADAPT) == "1"} { append defs "`define IODLY_ADAPT\n" }
if {[info exists ::env(IODLY_STATIC)]} { append defs "`define IODLY_STATIC $::env(IODLY_STATIC)\n" }
# RATE=<variant>: line rate = 50MHz x (MDIV + MDIV_FRAC/8) / ODIV x 2.
# Columns: MDIV MDIV_FRAC ODIV DELAY_1 FCLK_period_ns pclk_mult pclk_div (pclk = FCLK/4 from 50MHz)
array set RATE_TAB {
    1G     {20 0 2 21 2.0    5   2}
    1200M  {24 0 2 18 1.6667 3   1}
    1300M  {26 0 2 16 1.5385 13  4}
    1400M  {28 0 2 15 1.4286 7   2}
    1487M5 {14 7 1 14 1.3445 119 32}
    1600M  {16 0 1 13 1.25   4   1}
}
set RATE [expr {[info exists ::env(RATE)] ? $::env(RATE) : "1G"}]
if {![info exists RATE_TAB(${RATE})]} { error "unknown RATE ${RATE} (1G 1200M 1300M 1400M 1487M5 1600M)" }
lassign $RATE_TAB(${RATE}) R_MDIV R_FRAC R_ODIV R_DLY1 R_FPER R_PMUL R_PDIV
# DELAY1=<taps> overrides the IP's DELAY_1 (sampling-offset sweep)
if {[info exists ::env(DELAY1)]} { set R_DLY1 $::env(DELAY1) }
# TX_TLVDS=1: true-LVDS output buffer (TLVDS_OBUF, IO_TYPE=LVDS25) instead of the emulated LVPECL33E
if {[info exists ::env(TX_TLVDS)] && $::env(TX_TLVDS) == "1"} { append defs "`define TX_TLVDS\n" }
append defs "`define RATE_MDIV ${R_MDIV}\n`define RATE_MDIV_FRAC ${R_FRAC}\n`define RATE_ODIV ${R_ODIV}\n`define RATE_DELAY1 ${R_DLY1}\n"
set fh [open defines_gen.v w]; puts -nonewline $fh $defs; close $fh
add_file -type verilog [file normalize defines_gen.v]
add_file -type verilog [file normalize ${SRC_DIR}/top.v]

# BERT core (rtl/bert, Veryl output - run `veryl build` there after edits)
add_file -type verilog [file normalize ${RTL_DIR}/bert/prbs_pkg.sv]
add_file -type verilog [file normalize ${RTL_DIR}/bert/prbs_gen.sv]
add_file -type verilog [file normalize ${RTL_DIR}/bert/prbs_chk.sv]
add_file -type verilog [file normalize ${RTL_DIR}/bert/bert_counters.sv]
add_file -type verilog [file normalize ${RTL_DIR}/bert/bert_core.sv]
add_file -type verilog [file normalize ${RTL_DIR}/bert/bert_host.sv]

if {${TARGET} == "tangprimer25k"} {
    # Own CDR (rtl/oscdr, Veryl output) + GW5A PHY wrapper
    add_file -type verilog [file normalize ${RTL_DIR}/oscdr/os_cdr.sv]
    add_file -type verilog [file normalize ${RTL_DIR}/oscdr/bit_gearbox.sv]
    add_file -type verilog [file normalize ${SRC_DIR}/oscdr_phy_gw5a.v]
    add_file -type verilog [file normalize ${SRC_DIR}/ip_phy_gw5a.v]

    add_file -type verilog [file normalize ${RTL_DIR}/uart/uart_tx.sv]
    add_file -type verilog [file normalize ${RTL_DIR}/uart/uart_rx.sv]
    add_file -type verilog [file normalize ${SRC_DIR}/pll_rx_500m_4ph/pll_rx_500m_4ph.v]
    add_file -type verilog [file normalize ${SRC_DIR}/pll_tx_500m/pll_tx_500m.v]

    # EasyCDR IP (only used with `define USE_EASYCDR_IP): raw 16-bit, 1Gbps
    set_option -include_path [file normalize ${SRC_DIR}/easycdr_1912]
    add_file -type verilog [file normalize ${SRC_DIR}/easycdr_1912/EasyCDR_Top.v]
    add_file -type verilog [file normalize ${SRC_DIR}/easycdr_1912/EasyCDR.v]
}
if {${TARGET} == "tangnano9k_pmod"} {
    # TX-only PRBS source (999Mbps from the 27MHz crystal)
    add_file -type verilog [file normalize ${SRC_DIR}/pll_tx_4995/pll_tx_4995.v]
}

set TLVDS  [expr {[info exists ::env(TX_TLVDS)] && $::env(TX_TLVDS) == "1"}]
set DIRECT [expr {[info exists ::env(TX_DIRECT)] && $::env(TX_DIRECT) == "1"}]
if {${TLVDS} || ${DIRECT}} {
    set fh [open ${SRC_DIR}/pins.cst r]; set cst [read $fh]; close $fh
    if {${TLVDS}} {
        # true LVDS on the serial output: same attributes as the DisplayPort lanes (LVDS25 DRIVE=6)
        set cst [string map [list {IO_PORT "o_serial_p" IO_TYPE=LVPECL33E PULL_MODE=NONE DRIVE=16 BANK_VCCIO=3.3;} {IO_PORT "o_serial_p" IO_TYPE=LVDS25 PULL_MODE=NONE DRIVE=6 BANK_VCCIO=3.3;}] $cst]
    }
    if {${DIRECT}} {
        # TX_DIRECT=1: serial output on pmod0 pins 1/7 (F5/G5) for a direct-wire loop to pmod2 pins 1/7
        # (no ExtEasyCDR modules / USB-C cable); the IODELAY tone input normally on F5/G5 is dropped
        set cst [string map [list {IO_LOC "o_serial_p" G7,G8;} {IO_LOC "o_serial_p" F5,G5;} {IO_LOC "i_tone_p" F5,G5;} {}] $cst]
    }
    set fh [open pins_gen.cst w]; puts -nonewline $fh $cst; close $fh
    add_file -type cst [file normalize pins_gen.cst]
} else {
    add_file -type cst [file normalize ${SRC_DIR}/pins.cst]
}
if {${USE_IP}} {
    # timing_ip.sdc is a template: @FP@ / @FH@ = FCLK period / half, @PM@ / @PD@ = pclk multiply / divide from 50MHz
    set fh [open ${SRC_DIR}/timing_ip.sdc r]; set sdc [read $fh]; close $fh
    set sdc [string map [list @FP@ ${R_FPER} @FH@ [expr {${R_FPER} / 2.0}] @PM@ ${R_PMUL} @PD@ ${R_PDIV}] $sdc]
    set fh [open timing_gen.sdc w]; puts -nonewline $fh $sdc; close $fh
    add_file -type sdc [file normalize timing_gen.sdc]
} else {
    set fh [open ${SRC_DIR}/timing.sdc r]; set sdc [read $fh]; close $fh
    set sdc [string map [list @FP@ ${R_FPER} @FH@ [expr {${R_FPER} / 2.0}] @PM@ ${R_PMUL} @PD@ ${R_PDIV}] $sdc]
    set fh [open timing_gen.sdc w]; puts -nonewline $fh $sdc; close $fh
    add_file -type sdc [file normalize timing_gen.sdc]
}

run all
