PROJECT_NAME := i2c_slave
SRCS := $(wildcard ../../rtl/i2c_slave/*.sv) $(wildcard src/$(TARGET)/*.cst) $(wildcard src/$(TARGET)/*.sdc) $(wildcard src/$(TARGET)/*.sv) project.tcl

include ../build_gowin.mk