set SRC_DIR       [lindex $argv 0]
set RTL_DIR       [lindex $argv 1]
set TARGET        [lindex $argv 2]
set DEVICE_FAMILY [lindex $argv 3]
set DEVICE_PART   [lindex $argv 4]
set PROJECT_NAME  [lindex $argv 5]

set_option -output_base_name ${PROJECT_NAME}
set_device -name $DEVICE_FAMILY $DEVICE_PART

set_option -verilog_std sysv2017
set_option -print_all_synthesis_warning 1
set_option -top_module top
set_option -place_option 1
set_option -route_option 2

if {${TARGET} == "tangprimer25k"} {
    set_option -use_cpu_as_gpio 1
    # B2 / C2 (status LEDs) are dual-purpose configuration pins.
    set_option -use_i2c_as_gpio 1
    set_option -use_done_as_gpio 1
    set_option -use_ready_as_gpio 1
    set_option -use_sspi_as_gpio 1
}

# Build variant from the environment: RATE=720P (default 1080p60)
set RATE [expr {[info exists ::env(RATE)] ? $::env(RATE) : "1080P"}]
set fh [open defines_gen.v w]
puts $fh "// generated by project.tcl"
if {${RATE} == "720P"} { puts $fh "`define RATE_720P" }
# TX_SLOT=PMOD1: TX module on PMOD1, scope taps move to PMOD2
set TX_SLOT [expr {[info exists ::env(TX_SLOT)] ? $::env(TX_SLOT) : "PMOD2"}]
if {${TX_SLOT} == "PMOD1"} { puts $fh "`define TX_PMOD1" }
# TX_CLK=ODDR: send the TMDS clock lane through an ODDR on the pixel clock
# instead of an OSER10 (avoids needing tx_fclk in the clock pad's bank)
if {[info exists ::env(TX_CLK)] && $::env(TX_CLK) == "ODDR"} { puts $fh "`define TX_CLK_ODDR" }
close $fh
add_file -type verilog [file normalize defines_gen.v]

set CAPTURE_DIR [file normalize ${SRC_DIR}/../../../dvi_capture/src/${TARGET}]

# --- Veryl-generated cores ---
add_file -type verilog [file normalize ${RTL_DIR}/dvi_in/dvi_in.sv]
add_file -type verilog [file normalize ${RTL_DIR}/dvi_out/dvi_out.sv]
add_file -type verilog [file normalize ${RTL_DIR}/uart/uart_tx.sv]
add_file -type verilog [file normalize ${RTL_DIR}/uart/uart_rx.sv]

# --- RX PHY shared with dvi_capture ---
add_file -type verilog ${CAPTURE_DIR}/iser10_lane.sv
add_file -type verilog ${CAPTURE_DIR}/dvi_in_phy.sv
add_file -type verilog ${CAPTURE_DIR}/reset_seq.sv

# --- Loopback ---
foreach f {loop_pattern.sv frame_sum.sv loop_check.sv loop_report.sv top.sv} {
    add_file -type verilog [file normalize ${SRC_DIR}/${f}]
}
add_file -type verilog [file normalize ${SRC_DIR}/ip/gowin_pll_27.v]
add_file -type verilog [file normalize ${SRC_DIR}/ip/pll_tx_1080p/pll_tx_1080p.v]
add_file -type verilog [file normalize ${SRC_DIR}/ip/pll_rx_1080p/pll_rx_1080p.v]

# Pad variants from the environment (pins.cst holds the defaults):
#   TX_IO = LVPECL33E_16 (default) | LVCMOS33D_8 | ...   <IO_TYPE>_<DRIVE>
#   CTLE  = HIGH (default) | MEDIUM | LOW | OFF          RX equalizer
set TX_IO [expr {[info exists ::env(TX_IO)] ? $::env(TX_IO) : "LVPECL33E_16"}]
set CTLE  [expr {[info exists ::env(CTLE)]  ? $::env(CTLE)  : "HIGH"}]
regexp {^(.+)_([0-9]+)$} ${TX_IO} -> TX_IOTYPE TX_DRIVE
set fh [open ${SRC_DIR}/pins.cst r]; set cst [read $fh]; close $fh
if {${TX_SLOT} == "PMOD1"} {
    # Sipeed Pmod DVI order: pin1 = D2, pin2 = D1, pin3 = D0, pin4 = CLK
    set cst [string map [list \
        {IO_LOC "tx_clk_p" C11}     {IO_LOC "tx_clk_p" L5} \
        {IO_LOC "tx_data_p[0]" B11} {IO_LOC "tx_data_p[0]" K11} \
        {IO_LOC "tx_data_p[1]" D11} {IO_LOC "tx_data_p[1]" E11} \
        {IO_LOC "tx_data_p[2]" G11} {IO_LOC "tx_data_p[2]" A11} \
        {IO_LOC "dbg[0]" A11}       {IO_LOC "dbg[0]" G11} \
        {IO_LOC "dbg[1]" E11}       {IO_LOC "dbg[1]" D11} \
        {IO_LOC "dbg[2]" K11}       {IO_LOC "dbg[2]" B11} \
        {IO_LOC "dbg[3]" L5}        {IO_LOC "dbg[3]" C11}] $cst]
}
set cst [string map [list "IO_TYPE=LVPECL33E PULL_MODE=NONE DRIVE=16" "IO_TYPE=${TX_IOTYPE} PULL_MODE=NONE DRIVE=${TX_DRIVE}" "CTLE=HIGH" "CTLE=${CTLE}"] $cst]
set fh [open pins_gen.cst w]; puts -nonewline $fh $cst; close $fh
add_file -type cst [file normalize pins_gen.cst]
if {${RATE} == "720P"} {
    add_file -type sdc [file normalize ${SRC_DIR}/timing_720p.sdc]
} else {
    add_file -type sdc [file normalize ${SRC_DIR}/timing.sdc]
}

run all
