set SRC_DIR       [lindex $argv 0]
set RTL_DIR       [lindex $argv 1]
set TARGET        [lindex $argv 2]
set DEVICE_FAMILY [lindex $argv 3]
set DEVICE_PART   [lindex $argv 4]
set PROJECT_NAME  [lindex $argv 5]

set_option -output_base_name ${PROJECT_NAME}
set_option -verilog_std sysv2017
set_option -print_all_synthesis_warning 1
set_option -top_module top
set_option -place_option 2
set_option -route_option 2
set_option -gen_verilog_sim_netlist 1
set_device -name $DEVICE_FAMILY $DEVICE_PART
if {${TARGET} == "tangprimer25k"} {
    set_option -use_cpu_as_gpio 1
    set_option -use_i2c_as_gpio 1
}

set defs "// generated by project.tcl\n"
# USB_FS_ONLY=1: HS_CAPABLE=0 (no chirp) -> the device enumerates at full speed
if {[info exists ::env(USB_FS_ONLY)] && $::env(USB_FS_ONLY) == "1"} { append defs "`define USB_FS_ONLY\n" }
if {[info exists ::env(CAP_OS)] && $::env(CAP_OS) == "1"} { append defs "`define CAP_OS\n" }
if {[info exists ::env(CAP_CMP)] && $::env(CAP_CMP) == "1"} { append defs "`define CAP_CMP\n" }
if {[info exists ::env(BULK_IN_FULL_ONLY)] && $::env(BULK_IN_FULL_ONLY) == "1"} { append defs "`define BULK_IN_FULL_ONLY 1\n" } else { append defs "`define BULK_IN_FULL_ONLY 0\n" }
set fh [open defines_gen.v w]; puts -nonewline $fh $defs; close $fh
add_file -type verilog [file normalize defines_gen.v]
add_file -type verilog [file normalize ${SRC_DIR}/top.v]
add_file -type verilog [file normalize ${SRC_DIR}/pll_usb/pll_usb.v]
add_file -type verilog [file normalize ${SRC_DIR}/pll_usb_os/pll_usb_os.v]
# USB core (rtl/usb, Veryl output - run `veryl build` there after edits)
foreach f {usb_pkg usb_phy_rx usb_phy_tx usb_phy usb_phy_bridge usb_sie usb_descriptor_rom usb_device} {
    add_file -type verilog [file normalize ${RTL_DIR}/usb/${f}.sv]
}
# PHY front end in the 120 MHz oversampler domain (the 60 MHz UTMI-FIFO variant is usb_phy_gowin.v + usb_hs_os32.v)
add_file -type verilog [file normalize ${RTL_DIR}/usb/gowin/usb_phy_gowin_p.v]
# HS clock/data recovery (rtl/oscdr, Veryl output)
add_file -type verilog [file normalize ${RTL_DIR}/oscdr/os_cdr.sv]
add_file -type verilog [file normalize ${RTL_DIR}/oscdr/bit_gearbox.sv]
add_file -type verilog [file normalize ${RTL_DIR}/uart/uart_tx.sv]
add_file -type verilog [file normalize ${RTL_DIR}/uart/uart_rx.sv]

# Pmod slot assignment: USB_PMOD_A / USB_PMOD_B = pmod0 | pmod1 | pmod2 (Dock silkscreen),
# resolved through eda/targets/tangprimer25k/pmod_ports.csv into pins_gen.cst
set PMOD_A [expr {[info exists ::env(USB_PMOD_A)] ? $::env(USB_PMOD_A) : "pmod2"}]
set PMOD_B [expr {[info exists ::env(USB_PMOD_B)] ? $::env(USB_PMOD_B) : "pmod1"}]
set fh [open [file normalize ${SRC_DIR}/../../../targets/tangprimer25k/pmod_ports.csv] r]
array set BALL {}
foreach line [split [read $fh] "\n"] {
    if {[regexp {^(pmod[0-2]_[0-9]+),([A-Z][0-9]+)} $line -> k v]} { set BALL($k) $v }
}
close $fh
proc ball {slot pin} { global BALL; return $BALL(${slot}_${pin}) }
set fh [open ${SRC_DIR}/pins.cst r]; set cst [read $fh]; close $fh
set cst [string map [list \
    @RX_DP@   [ball $PMOD_A 1]  @RX_DN@   [ball $PMOD_A 7] \
    @RXDP_P@  [ball $PMOD_A 2]  @RXDP_N@  [ball $PMOD_A 8] \
    @RXDN_P@  [ball $PMOD_A 3]  @RXDN_N@  [ball $PMOD_A 9] \
    @TERM_DP@ [ball $PMOD_A 4]  @TERM_DN@ [ball $PMOD_A 10] \
    @TX_DP@   [ball $PMOD_B 1]  @TX_DN@   [ball $PMOD_B 7] \
    @PULLUP@  [ball $PMOD_B 2]  @VBUS@    [ball $PMOD_B 3] \
    @TX_DRIVE@ [expr {[info exists ::env(TX_DRIVE)] ? $::env(TX_DRIVE) : 16}]] $cst]   ;# 16 mA: with 8 mA the host rejected ~2.5% of our 512 B packets, with 4 mA the link barely works
set fh [open pins_gen.cst w]; puts -nonewline $fh $cst; close $fh
puts "usb_device: Pmod A = ${PMOD_A}, Pmod B = ${PMOD_B}"
add_file -type cst [file normalize pins_gen.cst]
add_file -type sdc [file normalize ${SRC_DIR}/timing.sdc]

run all
