BITSTREAM := impl/pnr/stp_emu.fs
SRCS := $(wildcard src/*.cst) $(wildcard src/*.sdc) $(wildcard src/*.sv) $(wildcard ../../rtl/segment_led/*.sv) $(wildcard ../../rtl/stp_emu/*.sv) project.tcl
DEVICE ?= GW1N-4B

include ../build_gowin.mk