PROJECT_NAME := stp_emu
SRCS := $(wildcard src/*.cst) $(wildcard src/*.sdc) $(wildcard src/*.sv) $(wildcard ../../rtl/segment_led/*.sv) $(wildcard ../../rtl/stp_emu/*.sv) project.tcl

include ../build_gowin.mk