PROJECT_NAME := lifegame_fram
SRCS := $(wildcard src/$(TARGET)/*.cst) $(wildcard src/$(TARGET)/*.sdc) $(wildcard src/$(TARGET)/*.sv) ../../rtl//chisel/lifegame_fram/lifegame_fram.v project.tcl
include ../build_gowin.mk
