#![doc = "Peripheral access API for DISPLAY_PORT_AUX_CH_SUBSYSTEM microcontrollers (generated using svd2rust v0.29.0 ( ))\n\nYou can find an overview of the generated API [here].\n\nAPI features to be included in the [next] svd2rust release can be generated by cloning the svd2rust [repository], checking out the above commit, and running `cargo doc --open`.\n\n[here]: https://docs.rs/svd2rust/0.29.0/svd2rust/#peripheral-api\n[next]: https://github.com/rust-embedded/svd2rust/blob/master/CHANGELOG.md#unreleased\n[repository]: https://github.com/rust-embedded/svd2rust"]
#![deny(dead_code)]
#![deny(improper_ctypes)]
#![deny(missing_docs)]
#![deny(no_mangle_generic_items)]
#![deny(non_shorthand_field_patterns)]
#![deny(overflowing_literals)]
#![deny(path_statements)]
#![deny(patterns_in_fns_without_body)]
#![deny(private_in_public)]
#![deny(unconditional_recursion)]
#![deny(unused_allocation)]
#![deny(unused_comparisons)]
#![deny(unused_parens)]
#![deny(while_true)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![no_std]
use core::marker::PhantomData;
use core::ops::Deref;
#[allow(unused_imports)]
use generic::*;
#[doc = r"Common register and bit access and modify traits"]
pub mod generic {
    use core::marker;
    #[doc = " Raw register type (`u8`, `u16`, `u32`, ...)"]
    pub trait RawReg:
        Copy
        + Default
        + From<bool>
        + core::ops::BitOr<Output = Self>
        + core::ops::BitAnd<Output = Self>
        + core::ops::BitOrAssign
        + core::ops::BitAndAssign
        + core::ops::Not<Output = Self>
        + core::ops::Shl<u8, Output = Self>
    {
        #[doc = " Mask for bits of width `WI`"]
        fn mask<const WI: u8>() -> Self;
        #[doc = " Mask for bits of width 1"]
        fn one() -> Self;
    }
    macro_rules! raw_reg {
        ($ U : ty , $ size : literal , $ mask : ident) => {
            impl RawReg for $U {
                #[inline(always)]
                fn mask<const WI: u8>() -> Self {
                    $mask::<WI>()
                }
                #[inline(always)]
                fn one() -> Self {
                    1
                }
            }
            const fn $mask<const WI: u8>() -> $U {
                <$U>::MAX >> ($size - WI)
            }
            impl FieldSpec for $U {
                type Ux = $U;
            }
        };
    }
    raw_reg!(u8, 8, mask_u8);
    raw_reg!(u16, 16, mask_u16);
    raw_reg!(u32, 32, mask_u32);
    raw_reg!(u64, 64, mask_u64);
    #[doc = " Raw register type"]
    pub trait RegisterSpec {
        #[doc = " Raw register type (`u8`, `u16`, `u32`, ...)."]
        type Ux: RawReg;
    }
    #[doc = " Raw field type"]
    pub trait FieldSpec: Sized {
        #[doc = " Raw field type (`u8`, `u16`, `u32`, ...)."]
        type Ux: Copy + PartialEq + From<Self>;
    }
    #[doc = " Trait implemented by readable registers to enable the `read` method."]
    #[doc = ""]
    #[doc = " Registers marked with `Writable` can be also be `modify`'ed."]
    pub trait Readable: RegisterSpec {
        #[doc = " Result from a call to `read` and argument to `modify`."]
        type Reader: From<R<Self>> + core::ops::Deref<Target = R<Self>>;
    }
    #[doc = " Trait implemented by writeable registers."]
    #[doc = ""]
    #[doc = " This enables the  `write`, `write_with_zero` and `reset` methods."]
    #[doc = ""]
    #[doc = " Registers marked with `Readable` can be also be `modify`'ed."]
    pub trait Writable: RegisterSpec {
        #[doc = " Writer type argument to `write`, et al."]
        type Writer: From<W<Self>> + core::ops::DerefMut<Target = W<Self>>;
        #[doc = " Specifies the register bits that are not changed if you pass `1` and are changed if you pass `0`"]
        const ZERO_TO_MODIFY_FIELDS_BITMAP: Self::Ux;
        #[doc = " Specifies the register bits that are not changed if you pass `0` and are changed if you pass `1`"]
        const ONE_TO_MODIFY_FIELDS_BITMAP: Self::Ux;
    }
    #[doc = " Reset value of the register."]
    #[doc = ""]
    #[doc = " This value is the initial value for the `write` method. It can also be directly written to the"]
    #[doc = " register by using the `reset` method."]
    pub trait Resettable: RegisterSpec {
        #[doc = " Reset value of the register."]
        const RESET_VALUE: Self::Ux;
        #[doc = " Reset value of the register."]
        #[inline(always)]
        fn reset_value() -> Self::Ux {
            Self::RESET_VALUE
        }
    }
    #[doc = " This structure provides volatile access to registers."]
    #[repr(transparent)]
    pub struct Reg<REG: RegisterSpec> {
        register: vcell::VolatileCell<REG::Ux>,
        _marker: marker::PhantomData<REG>,
    }
    unsafe impl<REG: RegisterSpec> Send for Reg<REG> where REG::Ux: Send {}
    impl<REG: RegisterSpec> Reg<REG> {
        #[doc = " Returns the underlying memory address of register."]
        #[doc = ""]
        #[doc = " ```ignore"]
        #[doc = " let reg_ptr = periph.reg.as_ptr();"]
        #[doc = " ```"]
        #[inline(always)]
        pub fn as_ptr(&self) -> *mut REG::Ux {
            self.register.as_ptr()
        }
    }
    impl<REG: Readable> Reg<REG> {
        #[doc = " Reads the contents of a `Readable` register."]
        #[doc = ""]
        #[doc = " You can read the raw contents of a register by using `bits`:"]
        #[doc = " ```ignore"]
        #[doc = " let bits = periph.reg.read().bits();"]
        #[doc = " ```"]
        #[doc = " or get the content of a particular field of a register:"]
        #[doc = " ```ignore"]
        #[doc = " let reader = periph.reg.read();"]
        #[doc = " let bits = reader.field1().bits();"]
        #[doc = " let flag = reader.field2().bit_is_set();"]
        #[doc = " ```"]
        #[inline(always)]
        pub fn read(&self) -> REG::Reader {
            REG::Reader::from(R {
                bits: self.register.get(),
                _reg: marker::PhantomData,
            })
        }
    }
    impl<REG: Resettable + Writable> Reg<REG> {
        #[doc = " Writes the reset value to `Writable` register."]
        #[doc = ""]
        #[doc = " Resets the register to its initial state."]
        #[inline(always)]
        pub fn reset(&self) {
            self.register.set(REG::RESET_VALUE)
        }
        #[doc = " Writes bits to a `Writable` register."]
        #[doc = ""]
        #[doc = " You can write raw bits into a register:"]
        #[doc = " ```ignore"]
        #[doc = " periph.reg.write(|w| unsafe { w.bits(rawbits) });"]
        #[doc = " ```"]
        #[doc = " or write only the fields you need:"]
        #[doc = " ```ignore"]
        #[doc = " periph.reg.write(|w| w"]
        #[doc = "     .field1().bits(newfield1bits)"]
        #[doc = "     .field2().set_bit()"]
        #[doc = "     .field3().variant(VARIANT)"]
        #[doc = " );"]
        #[doc = " ```"]
        #[doc = " or an alternative way of saying the same:"]
        #[doc = " ```ignore"]
        #[doc = " periph.reg.write(|w| {"]
        #[doc = "     w.field1().bits(newfield1bits);"]
        #[doc = "     w.field2().set_bit();"]
        #[doc = "     w.field3().variant(VARIANT)"]
        #[doc = " });"]
        #[doc = " ```"]
        #[doc = " In the latter case, other fields will be set to their reset value."]
        #[inline(always)]
        pub fn write<F>(&self, f: F)
        where
            F: FnOnce(&mut REG::Writer) -> &mut W<REG>,
        {
            self.register.set(
                f(&mut REG::Writer::from(W {
                    bits: REG::RESET_VALUE & !REG::ONE_TO_MODIFY_FIELDS_BITMAP
                        | REG::ZERO_TO_MODIFY_FIELDS_BITMAP,
                    _reg: marker::PhantomData,
                }))
                .bits,
            );
        }
    }
    impl<REG: Writable> Reg<REG> {
        #[doc = " Writes 0 to a `Writable` register."]
        #[doc = ""]
        #[doc = " Similar to `write`, but unused bits will contain 0."]
        #[doc = ""]
        #[doc = " # Safety"]
        #[doc = ""]
        #[doc = " Unsafe to use with registers which don't allow to write 0."]
        #[inline(always)]
        pub unsafe fn write_with_zero<F>(&self, f: F)
        where
            F: FnOnce(&mut REG::Writer) -> &mut W<REG>,
        {
            self.register.set(
                f(&mut REG::Writer::from(W {
                    bits: REG::Ux::default(),
                    _reg: marker::PhantomData,
                }))
                .bits,
            );
        }
    }
    impl<REG: Readable + Writable> Reg<REG> {
        #[doc = " Modifies the contents of the register by reading and then writing it."]
        #[doc = ""]
        #[doc = " E.g. to do a read-modify-write sequence to change parts of a register:"]
        #[doc = " ```ignore"]
        #[doc = " periph.reg.modify(|r, w| unsafe { w.bits("]
        #[doc = "    r.bits() | 3"]
        #[doc = " ) });"]
        #[doc = " ```"]
        #[doc = " or"]
        #[doc = " ```ignore"]
        #[doc = " periph.reg.modify(|_, w| w"]
        #[doc = "     .field1().bits(newfield1bits)"]
        #[doc = "     .field2().set_bit()"]
        #[doc = "     .field3().variant(VARIANT)"]
        #[doc = " );"]
        #[doc = " ```"]
        #[doc = " or an alternative way of saying the same:"]
        #[doc = " ```ignore"]
        #[doc = " periph.reg.modify(|_, w| {"]
        #[doc = "     w.field1().bits(newfield1bits);"]
        #[doc = "     w.field2().set_bit();"]
        #[doc = "     w.field3().variant(VARIANT)"]
        #[doc = " });"]
        #[doc = " ```"]
        #[doc = " Other fields will have the value they had before the call to `modify`."]
        #[inline(always)]
        pub fn modify<F>(&self, f: F)
        where
            for<'w> F: FnOnce(&REG::Reader, &'w mut REG::Writer) -> &'w mut W<REG>,
        {
            let bits = self.register.get();
            self.register.set(
                f(
                    &REG::Reader::from(R {
                        bits,
                        _reg: marker::PhantomData,
                    }),
                    &mut REG::Writer::from(W {
                        bits: bits & !REG::ONE_TO_MODIFY_FIELDS_BITMAP
                            | REG::ZERO_TO_MODIFY_FIELDS_BITMAP,
                        _reg: marker::PhantomData,
                    }),
                )
                .bits,
            );
        }
    }
    #[doc = " Register reader."]
    #[doc = ""]
    #[doc = " Result of the `read` methods of registers. Also used as a closure argument in the `modify`"]
    #[doc = " method."]
    pub struct R<REG: RegisterSpec + ?Sized> {
        pub(crate) bits: REG::Ux,
        _reg: marker::PhantomData<REG>,
    }
    impl<REG: RegisterSpec> R<REG> {
        #[doc = " Reads raw bits from register."]
        #[inline(always)]
        pub fn bits(&self) -> REG::Ux {
            self.bits
        }
    }
    impl<REG: RegisterSpec, FI> PartialEq<FI> for R<REG>
    where
        REG::Ux: PartialEq,
        FI: Copy,
        REG::Ux: From<FI>,
    {
        #[inline(always)]
        fn eq(&self, other: &FI) -> bool {
            self.bits.eq(&REG::Ux::from(*other))
        }
    }
    #[doc = " Register writer."]
    #[doc = ""]
    #[doc = " Used as an argument to the closures in the `write` and `modify` methods of the register."]
    pub struct W<REG: RegisterSpec + ?Sized> {
        #[doc = "Writable bits"]
        pub(crate) bits: REG::Ux,
        _reg: marker::PhantomData<REG>,
    }
    impl<REG: RegisterSpec> W<REG> {
        #[doc = " Writes raw bits to the register."]
        #[doc = ""]
        #[doc = " # Safety"]
        #[doc = ""]
        #[doc = " Read datasheet or reference manual to find what values are allowed to pass."]
        #[inline(always)]
        pub unsafe fn bits(&mut self, bits: REG::Ux) -> &mut Self {
            self.bits = bits;
            self
        }
    }
    #[doc(hidden)]
    pub struct FieldReaderRaw<FI = u8>
    where
        FI: FieldSpec,
    {
        pub(crate) bits: FI::Ux,
        _reg: marker::PhantomData<FI>,
    }
    impl<FI: FieldSpec> FieldReaderRaw<FI> {
        #[doc = " Creates a new instance of the reader."]
        #[allow(unused)]
        #[inline(always)]
        pub(crate) fn new(bits: FI::Ux) -> Self {
            Self {
                bits,
                _reg: marker::PhantomData,
            }
        }
    }
    #[doc(hidden)]
    pub struct BitReaderRaw<FI = bool> {
        pub(crate) bits: bool,
        _reg: marker::PhantomData<FI>,
    }
    impl<FI> BitReaderRaw<FI> {
        #[doc = " Creates a new instance of the reader."]
        #[allow(unused)]
        #[inline(always)]
        pub(crate) fn new(bits: bool) -> Self {
            Self {
                bits,
                _reg: marker::PhantomData,
            }
        }
    }
    #[doc = " Field reader."]
    #[doc = ""]
    #[doc = " Result of the `read` methods of fields."]
    pub type FieldReader<FI = u8> = FieldReaderRaw<FI>;
    #[doc = " Bit-wise field reader"]
    pub type BitReader<FI = bool> = BitReaderRaw<FI>;
    impl<FI: FieldSpec> FieldReader<FI> {
        #[doc = " Reads raw bits from field."]
        #[inline(always)]
        pub fn bits(&self) -> FI::Ux {
            self.bits
        }
    }
    impl<FI> PartialEq<FI> for FieldReader<FI>
    where
        FI: FieldSpec + Copy,
    {
        #[inline(always)]
        fn eq(&self, other: &FI) -> bool {
            self.bits.eq(&FI::Ux::from(*other))
        }
    }
    impl<FI> PartialEq<FI> for BitReader<FI>
    where
        FI: Copy,
        bool: From<FI>,
    {
        #[inline(always)]
        fn eq(&self, other: &FI) -> bool {
            self.bits.eq(&bool::from(*other))
        }
    }
    impl<FI> BitReader<FI> {
        #[doc = " Value of the field as raw bits."]
        #[inline(always)]
        pub fn bit(&self) -> bool {
            self.bits
        }
        #[doc = " Returns `true` if the bit is clear (0)."]
        #[inline(always)]
        pub fn bit_is_clear(&self) -> bool {
            !self.bit()
        }
        #[doc = " Returns `true` if the bit is set (1)."]
        #[inline(always)]
        pub fn bit_is_set(&self) -> bool {
            self.bit()
        }
    }
    #[doc(hidden)]
    pub struct Safe;
    #[doc(hidden)]
    pub struct Unsafe;
    #[doc(hidden)]
    pub struct FieldWriterRaw<'a, REG, const WI: u8, const O: u8, FI = u8, Safety = Unsafe>
    where
        REG: Writable + RegisterSpec,
        FI: FieldSpec,
    {
        pub(crate) w: &'a mut REG::Writer,
        _field: marker::PhantomData<(FI, Safety)>,
    }
    impl<'a, REG, const WI: u8, const O: u8, FI, Safety> FieldWriterRaw<'a, REG, WI, O, FI, Safety>
    where
        REG: Writable + RegisterSpec,
        FI: FieldSpec,
    {
        #[doc = " Creates a new instance of the writer"]
        #[allow(unused)]
        #[inline(always)]
        pub(crate) fn new(w: &'a mut REG::Writer) -> Self {
            Self {
                w,
                _field: marker::PhantomData,
            }
        }
    }
    #[doc(hidden)]
    pub struct BitWriterRaw<'a, REG, const O: u8, FI = bool, M = BitM>
    where
        REG: Writable + RegisterSpec,
        bool: From<FI>,
    {
        pub(crate) w: &'a mut REG::Writer,
        _field: marker::PhantomData<(FI, M)>,
    }
    impl<'a, REG, const O: u8, FI, M> BitWriterRaw<'a, REG, O, FI, M>
    where
        REG: Writable + RegisterSpec,
        bool: From<FI>,
    {
        #[doc = " Creates a new instance of the writer"]
        #[allow(unused)]
        #[inline(always)]
        pub(crate) fn new(w: &'a mut REG::Writer) -> Self {
            Self {
                w,
                _field: marker::PhantomData,
            }
        }
    }
    #[doc = " Write field Proxy with unsafe `bits`"]
    pub type FieldWriter<'a, REG, const WI: u8, const O: u8, FI = u8> =
        FieldWriterRaw<'a, REG, WI, O, FI, Unsafe>;
    #[doc = " Write field Proxy with safe `bits`"]
    pub type FieldWriterSafe<'a, REG, const WI: u8, const O: u8, FI = u8> =
        FieldWriterRaw<'a, REG, WI, O, FI, Safe>;
    impl<'a, REG, const WI: u8, const OF: u8, FI> FieldWriter<'a, REG, WI, OF, FI>
    where
        REG: Writable + RegisterSpec,
        FI: FieldSpec,
    {
        #[doc = " Field width"]
        pub const WIDTH: u8 = WI;
    }
    impl<'a, REG, const WI: u8, const OF: u8, FI> FieldWriterSafe<'a, REG, WI, OF, FI>
    where
        REG: Writable + RegisterSpec,
        FI: FieldSpec,
    {
        #[doc = " Field width"]
        pub const WIDTH: u8 = WI;
    }
    macro_rules! bit_proxy {
        ($ writer : ident , $ mwv : ident) => {
            #[doc(hidden)]
            pub struct $mwv;
            #[doc = " Bit-wise write field proxy"]
            pub type $writer<'a, REG, const O: u8, FI = bool> = BitWriterRaw<'a, REG, O, FI, $mwv>;
            impl<'a, REG, const OF: u8, FI> $writer<'a, REG, OF, FI>
            where
                REG: Writable + RegisterSpec,
                bool: From<FI>,
            {
                #[doc = " Field width"]
                pub const WIDTH: u8 = 1;
            }
        };
    }
    macro_rules! impl_bit_proxy {
        ($ writer : ident) => {
            impl<'a, REG, const OF: u8, FI> $writer<'a, REG, OF, FI>
            where
                REG: Writable + RegisterSpec,
                bool: From<FI>,
            {
                #[doc = " Writes bit to the field"]
                #[inline(always)]
                pub fn bit(self, value: bool) -> &'a mut REG::Writer {
                    self.w.bits &= !(REG::Ux::one() << OF);
                    self.w.bits |= (REG::Ux::from(value) & REG::Ux::one()) << OF;
                    self.w
                }
                #[doc = " Writes `variant` to the field"]
                #[inline(always)]
                pub fn variant(self, variant: FI) -> &'a mut REG::Writer {
                    self.bit(bool::from(variant))
                }
            }
        };
    }
    bit_proxy!(BitWriter, BitM);
    bit_proxy!(BitWriter1S, Bit1S);
    bit_proxy!(BitWriter0C, Bit0C);
    bit_proxy!(BitWriter1C, Bit1C);
    bit_proxy!(BitWriter0S, Bit0S);
    bit_proxy!(BitWriter1T, Bit1T);
    bit_proxy!(BitWriter0T, Bit0T);
    impl<'a, REG, const WI: u8, const OF: u8, FI> FieldWriter<'a, REG, WI, OF, FI>
    where
        REG: Writable + RegisterSpec,
        FI: FieldSpec,
        REG::Ux: From<FI::Ux>,
    {
        #[doc = " Writes raw bits to the field"]
        #[doc = ""]
        #[doc = " # Safety"]
        #[doc = ""]
        #[doc = " Passing incorrect value can cause undefined behaviour. See reference manual"]
        #[inline(always)]
        pub unsafe fn bits(self, value: FI::Ux) -> &'a mut REG::Writer {
            self.w.bits &= !(REG::Ux::mask::<WI>() << OF);
            self.w.bits |= (REG::Ux::from(value) & REG::Ux::mask::<WI>()) << OF;
            self.w
        }
        #[doc = " Writes `variant` to the field"]
        #[inline(always)]
        pub fn variant(self, variant: FI) -> &'a mut REG::Writer {
            unsafe { self.bits(FI::Ux::from(variant)) }
        }
    }
    impl<'a, REG, const WI: u8, const OF: u8, FI> FieldWriterSafe<'a, REG, WI, OF, FI>
    where
        REG: Writable + RegisterSpec,
        FI: FieldSpec,
        REG::Ux: From<FI::Ux>,
    {
        #[doc = " Writes raw bits to the field"]
        #[inline(always)]
        pub fn bits(self, value: FI::Ux) -> &'a mut REG::Writer {
            self.w.bits &= !(REG::Ux::mask::<WI>() << OF);
            self.w.bits |= (REG::Ux::from(value) & REG::Ux::mask::<WI>()) << OF;
            self.w
        }
        #[doc = " Writes `variant` to the field"]
        #[inline(always)]
        pub fn variant(self, variant: FI) -> &'a mut REG::Writer {
            self.bits(FI::Ux::from(variant))
        }
    }
    impl_bit_proxy!(BitWriter);
    impl_bit_proxy!(BitWriter1S);
    impl_bit_proxy!(BitWriter0C);
    impl_bit_proxy!(BitWriter1C);
    impl_bit_proxy!(BitWriter0S);
    impl_bit_proxy!(BitWriter1T);
    impl_bit_proxy!(BitWriter0T);
    impl<'a, REG, const OF: u8, FI> BitWriter<'a, REG, OF, FI>
    where
        REG: Writable + RegisterSpec,
        bool: From<FI>,
    {
        #[doc = " Sets the field bit"]
        #[inline(always)]
        pub fn set_bit(self) -> &'a mut REG::Writer {
            self.w.bits |= REG::Ux::one() << OF;
            self.w
        }
        #[doc = " Clears the field bit"]
        #[inline(always)]
        pub fn clear_bit(self) -> &'a mut REG::Writer {
            self.w.bits &= !(REG::Ux::one() << OF);
            self.w
        }
    }
    impl<'a, REG, const OF: u8, FI> BitWriter1S<'a, REG, OF, FI>
    where
        REG: Writable + RegisterSpec,
        bool: From<FI>,
    {
        #[doc = " Sets the field bit"]
        #[inline(always)]
        pub fn set_bit(self) -> &'a mut REG::Writer {
            self.w.bits |= REG::Ux::one() << OF;
            self.w
        }
    }
    impl<'a, REG, const OF: u8, FI> BitWriter0C<'a, REG, OF, FI>
    where
        REG: Writable + RegisterSpec,
        bool: From<FI>,
    {
        #[doc = " Clears the field bit"]
        #[inline(always)]
        pub fn clear_bit(self) -> &'a mut REG::Writer {
            self.w.bits &= !(REG::Ux::one() << OF);
            self.w
        }
    }
    impl<'a, REG, const OF: u8, FI> BitWriter1C<'a, REG, OF, FI>
    where
        REG: Writable + RegisterSpec,
        bool: From<FI>,
    {
        #[doc = "Clears the field bit by passing one"]
        #[inline(always)]
        pub fn clear_bit_by_one(self) -> &'a mut REG::Writer {
            self.w.bits |= REG::Ux::one() << OF;
            self.w
        }
    }
    impl<'a, REG, const OF: u8, FI> BitWriter0S<'a, REG, OF, FI>
    where
        REG: Writable + RegisterSpec,
        bool: From<FI>,
    {
        #[doc = "Sets the field bit by passing zero"]
        #[inline(always)]
        pub fn set_bit_by_zero(self) -> &'a mut REG::Writer {
            self.w.bits &= !(REG::Ux::one() << OF);
            self.w
        }
    }
    impl<'a, REG, const OF: u8, FI> BitWriter1T<'a, REG, OF, FI>
    where
        REG: Writable + RegisterSpec,
        bool: From<FI>,
    {
        #[doc = "Toggle the field bit by passing one"]
        #[inline(always)]
        pub fn toggle_bit(self) -> &'a mut REG::Writer {
            self.w.bits |= REG::Ux::one() << OF;
            self.w
        }
    }
    impl<'a, REG, const OF: u8, FI> BitWriter0T<'a, REG, OF, FI>
    where
        REG: Writable + RegisterSpec,
        bool: From<FI>,
    {
        #[doc = "Toggle the field bit by passing zero"]
        #[inline(always)]
        pub fn toggle_bit(self) -> &'a mut REG::Writer {
            self.w.bits &= !(REG::Ux::one() << OF);
            self.w
        }
    }
    #[doc = " Access an array of `COUNT` items of type `T` with the items `STRIDE` bytes"]
    #[doc = " apart.  This is a zero-sized-type.  No objects of this type are ever"]
    #[doc = " actually created, it is only a convenience for wrapping pointer arithmetic."]
    #[doc = ""]
    #[doc = " There is no safe way to produce items of this type.  Unsafe code can produce"]
    #[doc = " references by pointer casting.  It is up to the unsafe code doing that, to"]
    #[doc = " ensure that the memory really is backed by appropriate content."]
    #[doc = ""]
    #[doc = " Typically, this is used for accessing hardware registers."]
    pub struct ArrayProxy<T, const COUNT: usize, const STRIDE: usize> {
        #[doc = " As well as providing a PhantomData, this field is non-public, and"]
        #[doc = " therefore ensures that code outside of this module can never create"]
        #[doc = " an ArrayProxy."]
        _array: marker::PhantomData<T>,
    }
    #[allow(clippy::len_without_is_empty)]
    impl<T, const C: usize, const S: usize> ArrayProxy<T, C, S> {
        #[doc = " Get a reference from an [ArrayProxy] with no bounds checking."]
        pub unsafe fn get_ref(&self, index: usize) -> &T {
            let base = self as *const Self as usize;
            let address = base + S * index;
            &*(address as *const T)
        }
        #[doc = " Get a reference from an [ArrayProxy], or return `None` if the index"]
        #[doc = " is out of bounds."]
        pub fn get(&self, index: usize) -> Option<&T> {
            if index < C {
                Some(unsafe { self.get_ref(index) })
            } else {
                None
            }
        }
        #[doc = " Return the number of items."]
        pub fn len(&self) -> usize {
            C
        }
    }
    impl<T, const C: usize, const S: usize> core::ops::Index<usize> for ArrayProxy<T, C, S> {
        type Output = T;
        fn index(&self, index: usize) -> &T {
            #[allow(clippy::no_effect)]
            [(); C][index];
            unsafe { self.get_ref(index) }
        }
    }
}
#[cfg(feature = "rt")]
extern "C" {}
#[doc(hidden)]
pub union Vector {
    pub _handler: unsafe extern "C" fn(),
    pub _reserved: usize,
}
#[cfg(feature = "rt")]
#[doc(hidden)]
#[no_mangle]
pub static __EXTERNAL_INTERRUPTS: [Vector; 0] = [];
#[doc = "SYSTEM"]
pub struct SYSTEM {
    _marker: PhantomData<*const ()>,
}
unsafe impl Send for SYSTEM {}
impl SYSTEM {
    #[doc = r"Pointer to the register block"]
    pub const PTR: *const system::RegisterBlock = 0x4000_0000 as *const _;
    #[doc = r"Return the pointer to the register block"]
    #[inline(always)]
    pub const fn ptr() -> *const system::RegisterBlock {
        Self::PTR
    }
}
impl Deref for SYSTEM {
    type Target = system::RegisterBlock;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        unsafe { &*Self::PTR }
    }
}
impl core::fmt::Debug for SYSTEM {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("SYSTEM").finish()
    }
}
#[doc = "SYSTEM"]
pub mod system {
    #[doc = r"Register block"]
    #[repr(C)]
    pub struct RegisterBlock {
        #[doc = "0x00 - "]
        pub id: ID,
        #[doc = "0x04 - "]
        pub clock_hz: CLOCK_HZ,
        #[doc = "0x08 - "]
        pub out: OUT,
        _reserved3: [u8; 0x04],
        #[doc = "0x10 - Hot Plug Detect status. DP 1.2 section 3.3."]
        pub hpd: HPD,
    }
    #[doc = "ID (rw) register accessor: an alias for `Reg<ID_SPEC>`"]
    pub type ID = crate::Reg<id::ID_SPEC>;
    #[doc = ""]
    pub mod id {
        #[doc = "Register `ID` reader"]
        pub struct R(crate::R<ID_SPEC>);
        impl core::ops::Deref for R {
            type Target = crate::R<ID_SPEC>;
            #[inline(always)]
            fn deref(&self) -> &Self::Target {
                &self.0
            }
        }
        impl From<crate::R<ID_SPEC>> for R {
            #[inline(always)]
            fn from(reader: crate::R<ID_SPEC>) -> Self {
                R(reader)
            }
        }
        #[doc = "Register `ID` writer"]
        pub struct W(crate::W<ID_SPEC>);
        impl core::ops::Deref for W {
            type Target = crate::W<ID_SPEC>;
            #[inline(always)]
            fn deref(&self) -> &Self::Target {
                &self.0
            }
        }
        impl core::ops::DerefMut for W {
            #[inline(always)]
            fn deref_mut(&mut self) -> &mut Self::Target {
                &mut self.0
            }
        }
        impl From<crate::W<ID_SPEC>> for W {
            #[inline(always)]
            fn from(writer: crate::W<ID_SPEC>) -> Self {
                W(writer)
            }
        }
        #[doc = "Field `ID` reader - "]
        pub type ID_R = crate::FieldReader<u32>;
        impl R {
            #[doc = "Bits 0:31"]
            #[inline(always)]
            pub fn id(&self) -> ID_R {
                ID_R::new(self.bits)
            }
        }
        impl W {
            #[doc = "Writes raw bits to the register."]
            #[inline(always)]
            pub unsafe fn bits(&mut self, bits: u32) -> &mut Self {
                self.0.bits(bits);
                self
            }
        }
        #[doc = "\n\nThis register you can [`read`](crate::generic::Reg::read), [`write_with_zero`](crate::generic::Reg::write_with_zero), [`reset`](crate::generic::Reg::reset), [`write`](crate::generic::Reg::write), [`modify`](crate::generic::Reg::modify). See [API](https://docs.rs/svd2rust/#read--modify--write-api).\n\nFor information about available fields see [id](index.html) module"]
        pub struct ID_SPEC;
        impl crate::RegisterSpec for ID_SPEC {
            type Ux = u32;
        }
        #[doc = "`read()` method returns [id::R](R) reader structure"]
        impl crate::Readable for ID_SPEC {
            type Reader = R;
        }
        #[doc = "`write(|w| ..)` method takes [id::W](W) writer structure"]
        impl crate::Writable for ID_SPEC {
            type Writer = W;
            const ZERO_TO_MODIFY_FIELDS_BITMAP: Self::Ux = 0;
            const ONE_TO_MODIFY_FIELDS_BITMAP: Self::Ux = 0;
        }
        #[doc = "`reset()` method sets ID to value 0"]
        impl crate::Resettable for ID_SPEC {
            const RESET_VALUE: Self::Ux = 0;
        }
    }
    #[doc = "CLOCK_HZ (rw) register accessor: an alias for `Reg<CLOCK_HZ_SPEC>`"]
    pub type CLOCK_HZ = crate::Reg<clock_hz::CLOCK_HZ_SPEC>;
    #[doc = ""]
    pub mod clock_hz {
        #[doc = "Register `CLOCK_HZ` reader"]
        pub struct R(crate::R<CLOCK_HZ_SPEC>);
        impl core::ops::Deref for R {
            type Target = crate::R<CLOCK_HZ_SPEC>;
            #[inline(always)]
            fn deref(&self) -> &Self::Target {
                &self.0
            }
        }
        impl From<crate::R<CLOCK_HZ_SPEC>> for R {
            #[inline(always)]
            fn from(reader: crate::R<CLOCK_HZ_SPEC>) -> Self {
                R(reader)
            }
        }
        #[doc = "Register `CLOCK_HZ` writer"]
        pub struct W(crate::W<CLOCK_HZ_SPEC>);
        impl core::ops::Deref for W {
            type Target = crate::W<CLOCK_HZ_SPEC>;
            #[inline(always)]
            fn deref(&self) -> &Self::Target {
                &self.0
            }
        }
        impl core::ops::DerefMut for W {
            #[inline(always)]
            fn deref_mut(&mut self) -> &mut Self::Target {
                &mut self.0
            }
        }
        impl From<crate::W<CLOCK_HZ_SPEC>> for W {
            #[inline(always)]
            fn from(writer: crate::W<CLOCK_HZ_SPEC>) -> Self {
                W(writer)
            }
        }
        #[doc = "Field `CLOCK_HZ` reader - "]
        pub type CLOCK_HZ_R = crate::FieldReader<u32>;
        impl R {
            #[doc = "Bits 0:31"]
            #[inline(always)]
            pub fn clock_hz(&self) -> CLOCK_HZ_R {
                CLOCK_HZ_R::new(self.bits)
            }
        }
        impl W {
            #[doc = "Writes raw bits to the register."]
            #[inline(always)]
            pub unsafe fn bits(&mut self, bits: u32) -> &mut Self {
                self.0.bits(bits);
                self
            }
        }
        #[doc = "\n\nThis register you can [`read`](crate::generic::Reg::read), [`write_with_zero`](crate::generic::Reg::write_with_zero), [`reset`](crate::generic::Reg::reset), [`write`](crate::generic::Reg::write), [`modify`](crate::generic::Reg::modify). See [API](https://docs.rs/svd2rust/#read--modify--write-api).\n\nFor information about available fields see [clock_hz](index.html) module"]
        pub struct CLOCK_HZ_SPEC;
        impl crate::RegisterSpec for CLOCK_HZ_SPEC {
            type Ux = u32;
        }
        #[doc = "`read()` method returns [clock_hz::R](R) reader structure"]
        impl crate::Readable for CLOCK_HZ_SPEC {
            type Reader = R;
        }
        #[doc = "`write(|w| ..)` method takes [clock_hz::W](W) writer structure"]
        impl crate::Writable for CLOCK_HZ_SPEC {
            type Writer = W;
            const ZERO_TO_MODIFY_FIELDS_BITMAP: Self::Ux = 0;
            const ONE_TO_MODIFY_FIELDS_BITMAP: Self::Ux = 0;
        }
        #[doc = "`reset()` method sets CLOCK_HZ to value 0"]
        impl crate::Resettable for CLOCK_HZ_SPEC {
            const RESET_VALUE: Self::Ux = 0;
        }
    }
    #[doc = "OUT (rw) register accessor: an alias for `Reg<OUT_SPEC>`"]
    pub type OUT = crate::Reg<out::OUT_SPEC>;
    #[doc = ""]
    pub mod out {
        #[doc = "Register `OUT` reader"]
        pub struct R(crate::R<OUT_SPEC>);
        impl core::ops::Deref for R {
            type Target = crate::R<OUT_SPEC>;
            #[inline(always)]
            fn deref(&self) -> &Self::Target {
                &self.0
            }
        }
        impl From<crate::R<OUT_SPEC>> for R {
            #[inline(always)]
            fn from(reader: crate::R<OUT_SPEC>) -> Self {
                R(reader)
            }
        }
        #[doc = "Register `OUT` writer"]
        pub struct W(crate::W<OUT_SPEC>);
        impl core::ops::Deref for W {
            type Target = crate::W<OUT_SPEC>;
            #[inline(always)]
            fn deref(&self) -> &Self::Target {
                &self.0
            }
        }
        impl core::ops::DerefMut for W {
            #[inline(always)]
            fn deref_mut(&mut self) -> &mut Self::Target {
                &mut self.0
            }
        }
        impl From<crate::W<OUT_SPEC>> for W {
            #[inline(always)]
            fn from(writer: crate::W<OUT_SPEC>) -> Self {
                W(writer)
            }
        }
        #[doc = "Field `OUT` reader - "]
        pub type OUT_R = crate::FieldReader<u32>;
        #[doc = "Field `OUT` writer - "]
        pub type OUT_W<'a, const O: u8> = crate::FieldWriterSafe<'a, OUT_SPEC, 32, O, u32>;
        impl R {
            #[doc = "Bits 0:31"]
            #[inline(always)]
            pub fn out(&self) -> OUT_R {
                OUT_R::new(self.bits)
            }
        }
        impl W {
            #[doc = "Bits 0:31"]
            #[inline(always)]
            #[must_use]
            pub fn out(&mut self) -> OUT_W<0> {
                OUT_W::new(self)
            }
            #[doc = "Writes raw bits to the register."]
            #[inline(always)]
            pub fn bits(&mut self, bits: u32) -> &mut Self {
                unsafe { self.0.bits(bits) };
                self
            }
        }
        #[doc = "\n\nThis register you can [`read`](crate::generic::Reg::read), [`write_with_zero`](crate::generic::Reg::write_with_zero), [`reset`](crate::generic::Reg::reset), [`write`](crate::generic::Reg::write), [`modify`](crate::generic::Reg::modify). See [API](https://docs.rs/svd2rust/#read--modify--write-api).\n\nFor information about available fields see [out](index.html) module"]
        pub struct OUT_SPEC;
        impl crate::RegisterSpec for OUT_SPEC {
            type Ux = u32;
        }
        #[doc = "`read()` method returns [out::R](R) reader structure"]
        impl crate::Readable for OUT_SPEC {
            type Reader = R;
        }
        #[doc = "`write(|w| ..)` method takes [out::W](W) writer structure"]
        impl crate::Writable for OUT_SPEC {
            type Writer = W;
            const ZERO_TO_MODIFY_FIELDS_BITMAP: Self::Ux = 0;
            const ONE_TO_MODIFY_FIELDS_BITMAP: Self::Ux = 0;
        }
        #[doc = "`reset()` method sets OUT to value 0"]
        impl crate::Resettable for OUT_SPEC {
            const RESET_VALUE: Self::Ux = 0;
        }
    }
    #[doc = "HPD (rw) register accessor: an alias for `Reg<HPD_SPEC>`"]
    pub type HPD = crate::Reg<hpd::HPD_SPEC>;
    #[doc = "Hot Plug Detect status. DP 1.2 section 3.3."]
    pub mod hpd {
        #[doc = "Register `HPD` reader"]
        pub struct R(crate::R<HPD_SPEC>);
        impl core::ops::Deref for R {
            type Target = crate::R<HPD_SPEC>;
            #[inline(always)]
            fn deref(&self) -> &Self::Target {
                &self.0
            }
        }
        impl From<crate::R<HPD_SPEC>> for R {
            #[inline(always)]
            fn from(reader: crate::R<HPD_SPEC>) -> Self {
                R(reader)
            }
        }
        #[doc = "Register `HPD` writer"]
        pub struct W(crate::W<HPD_SPEC>);
        impl core::ops::Deref for W {
            type Target = crate::W<HPD_SPEC>;
            #[inline(always)]
            fn deref(&self) -> &Self::Target {
                &self.0
            }
        }
        impl core::ops::DerefMut for W {
            #[inline(always)]
            fn deref_mut(&mut self) -> &mut Self::Target {
                &mut self.0
            }
        }
        impl From<crate::W<HPD_SPEC>> for W {
            #[inline(always)]
            fn from(writer: crate::W<HPD_SPEC>) -> Self {
                W(writer)
            }
        }
        #[doc = "Field `LEVEL` reader - Debounced HPD level. 1 = sink connected."]
        pub type LEVEL_R = crate::BitReader;
        #[doc = "Field `EVENT_PLUG` reader - Sticky plug event. Write 1 to clear."]
        pub type EVENT_PLUG_R = crate::BitReader;
        #[doc = "Field `EVENT_PLUG` writer - Sticky plug event. Write 1 to clear."]
        pub type EVENT_PLUG_W<'a, const O: u8> = crate::BitWriter<'a, HPD_SPEC, O>;
        #[doc = "Field `EVENT_UNPLUG` reader - Sticky unplug event. Write 1 to clear."]
        pub type EVENT_UNPLUG_R = crate::BitReader;
        #[doc = "Field `EVENT_UNPLUG` writer - Sticky unplug event. Write 1 to clear."]
        pub type EVENT_UNPLUG_W<'a, const O: u8> = crate::BitWriter<'a, HPD_SPEC, O>;
        impl R {
            #[doc = "Bit 0 - Debounced HPD level. 1 = sink connected."]
            #[inline(always)]
            pub fn level(&self) -> LEVEL_R {
                LEVEL_R::new((self.bits & 1) != 0)
            }
            #[doc = "Bit 1 - Sticky plug event. Write 1 to clear."]
            #[inline(always)]
            pub fn event_plug(&self) -> EVENT_PLUG_R {
                EVENT_PLUG_R::new(((self.bits >> 1) & 1) != 0)
            }
            #[doc = "Bit 2 - Sticky unplug event. Write 1 to clear."]
            #[inline(always)]
            pub fn event_unplug(&self) -> EVENT_UNPLUG_R {
                EVENT_UNPLUG_R::new(((self.bits >> 2) & 1) != 0)
            }
        }
        impl W {
            #[doc = "Bit 1 - Sticky plug event. Write 1 to clear."]
            #[inline(always)]
            #[must_use]
            pub fn event_plug(&mut self) -> EVENT_PLUG_W<1> {
                EVENT_PLUG_W::new(self)
            }
            #[doc = "Bit 2 - Sticky unplug event. Write 1 to clear."]
            #[inline(always)]
            #[must_use]
            pub fn event_unplug(&mut self) -> EVENT_UNPLUG_W<2> {
                EVENT_UNPLUG_W::new(self)
            }
            #[doc = "Writes raw bits to the register."]
            #[inline(always)]
            pub unsafe fn bits(&mut self, bits: u32) -> &mut Self {
                self.0.bits(bits);
                self
            }
        }
        #[doc = "Hot Plug Detect status. DP 1.2 section 3.3.\n\nThis register you can [`read`](crate::generic::Reg::read), [`write_with_zero`](crate::generic::Reg::write_with_zero), [`reset`](crate::generic::Reg::reset), [`write`](crate::generic::Reg::write), [`modify`](crate::generic::Reg::modify). See [API](https://docs.rs/svd2rust/#read--modify--write-api).\n\nFor information about available fields see [hpd](index.html) module"]
        pub struct HPD_SPEC;
        impl crate::RegisterSpec for HPD_SPEC {
            type Ux = u32;
        }
        #[doc = "`read()` method returns [hpd::R](R) reader structure"]
        impl crate::Readable for HPD_SPEC {
            type Reader = R;
        }
        #[doc = "`write(|w| ..)` method takes [hpd::W](W) writer structure"]
        impl crate::Writable for HPD_SPEC {
            type Writer = W;
            const ZERO_TO_MODIFY_FIELDS_BITMAP: Self::Ux = 0;
            const ONE_TO_MODIFY_FIELDS_BITMAP: Self::Ux = 0;
        }
        #[doc = "`reset()` method sets HPD to value 0"]
        impl crate::Resettable for HPD_SPEC {
            const RESET_VALUE: Self::Ux = 0;
        }
    }
}
#[doc = "SYSTEM_SERIALOUT"]
pub struct SYSTEM_SERIALOUT {
    _marker: PhantomData<*const ()>,
}
unsafe impl Send for SYSTEM_SERIALOUT {}
impl SYSTEM_SERIALOUT {
    #[doc = r"Pointer to the register block"]
    pub const PTR: *const system_serialout::RegisterBlock = 0x4000_0000 as *const _;
    #[doc = r"Return the pointer to the register block"]
    #[inline(always)]
    pub const fn ptr() -> *const system_serialout::RegisterBlock {
        Self::PTR
    }
}
impl Deref for SYSTEM_SERIALOUT {
    type Target = system_serialout::RegisterBlock;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        unsafe { &*Self::PTR }
    }
}
impl core::fmt::Debug for SYSTEM_SERIALOUT {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("SYSTEM_SERIALOUT").finish()
    }
}
#[doc = "SYSTEM_SERIALOUT"]
pub mod system_serialout {
    #[doc = r"Register block"]
    #[repr(C)]
    pub struct RegisterBlock {
        _reserved0: [u8; 0x0c],
        #[doc = "0x0c - "]
        pub serial_out: SERIAL_OUT,
    }
    #[doc = "SERIAL_OUT (rw) register accessor: an alias for `Reg<SERIAL_OUT_SPEC>`"]
    pub type SERIAL_OUT = crate::Reg<serial_out::SERIAL_OUT_SPEC>;
    #[doc = ""]
    pub mod serial_out {
        #[doc = "Register `SERIAL_OUT` reader"]
        pub struct R(crate::R<SERIAL_OUT_SPEC>);
        impl core::ops::Deref for R {
            type Target = crate::R<SERIAL_OUT_SPEC>;
            #[inline(always)]
            fn deref(&self) -> &Self::Target {
                &self.0
            }
        }
        impl From<crate::R<SERIAL_OUT_SPEC>> for R {
            #[inline(always)]
            fn from(reader: crate::R<SERIAL_OUT_SPEC>) -> Self {
                R(reader)
            }
        }
        #[doc = "Register `SERIAL_OUT` writer"]
        pub struct W(crate::W<SERIAL_OUT_SPEC>);
        impl core::ops::Deref for W {
            type Target = crate::W<SERIAL_OUT_SPEC>;
            #[inline(always)]
            fn deref(&self) -> &Self::Target {
                &self.0
            }
        }
        impl core::ops::DerefMut for W {
            #[inline(always)]
            fn deref_mut(&mut self) -> &mut Self::Target {
                &mut self.0
            }
        }
        impl From<crate::W<SERIAL_OUT_SPEC>> for W {
            #[inline(always)]
            fn from(writer: crate::W<SERIAL_OUT_SPEC>) -> Self {
                W(writer)
            }
        }
        #[doc = "Field `DATA` reader - "]
        pub type DATA_R = crate::FieldReader;
        #[doc = "Field `DATA` writer - "]
        pub type DATA_W<'a, const O: u8> = crate::FieldWriterSafe<'a, SERIAL_OUT_SPEC, 8, O>;
        #[doc = "Field `TXBUSY` reader - "]
        pub type TXBUSY_R = crate::BitReader<TXBUSY_A>;
        #[doc = "\n\nValue on reset: 0"]
        #[derive(Clone, Copy, Debug, PartialEq, Eq)]
        pub enum TXBUSY_A {
            #[doc = "1: `1`"]
            BUSY = 1,
            #[doc = "0: `0`"]
            IDLE = 0,
        }
        impl From<TXBUSY_A> for bool {
            #[inline(always)]
            fn from(variant: TXBUSY_A) -> Self {
                variant as u8 != 0
            }
        }
        impl TXBUSY_R {
            #[doc = "Get enumerated values variant"]
            #[inline(always)]
            pub fn variant(&self) -> TXBUSY_A {
                match self.bits {
                    true => TXBUSY_A::BUSY,
                    false => TXBUSY_A::IDLE,
                }
            }
            #[doc = "Checks if the value of the field is `BUSY`"]
            #[inline(always)]
            pub fn is_busy(&self) -> bool {
                *self == TXBUSY_A::BUSY
            }
            #[doc = "Checks if the value of the field is `IDLE`"]
            #[inline(always)]
            pub fn is_idle(&self) -> bool {
                *self == TXBUSY_A::IDLE
            }
        }
        impl R {
            #[doc = "Bits 0:7"]
            #[inline(always)]
            pub fn data(&self) -> DATA_R {
                DATA_R::new((self.bits & 0xff) as u8)
            }
            #[doc = "Bit 8"]
            #[inline(always)]
            pub fn txbusy(&self) -> TXBUSY_R {
                TXBUSY_R::new(((self.bits >> 8) & 1) != 0)
            }
        }
        impl W {
            #[doc = "Bits 0:7"]
            #[inline(always)]
            #[must_use]
            pub fn data(&mut self) -> DATA_W<0> {
                DATA_W::new(self)
            }
            #[doc = "Writes raw bits to the register."]
            #[inline(always)]
            pub unsafe fn bits(&mut self, bits: u32) -> &mut Self {
                self.0.bits(bits);
                self
            }
        }
        #[doc = "\n\nThis register you can [`read`](crate::generic::Reg::read), [`write_with_zero`](crate::generic::Reg::write_with_zero), [`reset`](crate::generic::Reg::reset), [`write`](crate::generic::Reg::write), [`modify`](crate::generic::Reg::modify). See [API](https://docs.rs/svd2rust/#read--modify--write-api).\n\nFor information about available fields see [serial_out](index.html) module"]
        pub struct SERIAL_OUT_SPEC;
        impl crate::RegisterSpec for SERIAL_OUT_SPEC {
            type Ux = u32;
        }
        #[doc = "`read()` method returns [serial_out::R](R) reader structure"]
        impl crate::Readable for SERIAL_OUT_SPEC {
            type Reader = R;
        }
        #[doc = "`write(|w| ..)` method takes [serial_out::W](W) writer structure"]
        impl crate::Writable for SERIAL_OUT_SPEC {
            type Writer = W;
            const ZERO_TO_MODIFY_FIELDS_BITMAP: Self::Ux = 0;
            const ONE_TO_MODIFY_FIELDS_BITMAP: Self::Ux = 0;
        }
        #[doc = "`reset()` method sets SERIAL_OUT to value 0"]
        impl crate::Resettable for SERIAL_OUT_SPEC {
            const RESET_VALUE: Self::Ux = 0;
        }
    }
}
#[doc = "BUFFER"]
pub struct AUX_CH {
    _marker: PhantomData<*const ()>,
}
unsafe impl Send for AUX_CH {}
impl AUX_CH {
    #[doc = r"Pointer to the register block"]
    pub const PTR: *const aux_ch::RegisterBlock = 0x4001_0000 as *const _;
    #[doc = r"Return the pointer to the register block"]
    #[inline(always)]
    pub const fn ptr() -> *const aux_ch::RegisterBlock {
        Self::PTR
    }
}
impl Deref for AUX_CH {
    type Target = aux_ch::RegisterBlock;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        unsafe { &*Self::PTR }
    }
}
impl core::fmt::Debug for AUX_CH {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("AUX_CH").finish()
    }
}
#[doc = "BUFFER"]
pub mod aux_ch {
    #[doc = r"Register block"]
    #[repr(C)]
    pub struct RegisterBlock {
        #[doc = "0x00..0x400 - "]
        pub buffer: [BUFFER; 256],
        #[doc = "0x400 - "]
        pub operation_status: OPERATION_STATUS,
        #[doc = "0x404 - "]
        pub interrupt_status: INTERRUPT_STATUS,
        #[doc = "0x408 - "]
        pub rx_count: RX_COUNT,
        #[doc = "0x40c - "]
        pub rx_index: RX_INDEX,
        #[doc = "0x410 - "]
        pub tx_count: TX_COUNT,
        #[doc = "0x414 - "]
        pub tx_index: TX_INDEX,
    }
    #[doc = "BUFFER (rw) register accessor: an alias for `Reg<BUFFER_SPEC>`"]
    pub type BUFFER = crate::Reg<buffer::BUFFER_SPEC>;
    #[doc = ""]
    pub mod buffer {
        #[doc = "Register `BUFFER[%s]` reader"]
        pub struct R(crate::R<BUFFER_SPEC>);
        impl core::ops::Deref for R {
            type Target = crate::R<BUFFER_SPEC>;
            #[inline(always)]
            fn deref(&self) -> &Self::Target {
                &self.0
            }
        }
        impl From<crate::R<BUFFER_SPEC>> for R {
            #[inline(always)]
            fn from(reader: crate::R<BUFFER_SPEC>) -> Self {
                R(reader)
            }
        }
        #[doc = "Register `BUFFER[%s]` writer"]
        pub struct W(crate::W<BUFFER_SPEC>);
        impl core::ops::Deref for W {
            type Target = crate::W<BUFFER_SPEC>;
            #[inline(always)]
            fn deref(&self) -> &Self::Target {
                &self.0
            }
        }
        impl core::ops::DerefMut for W {
            #[inline(always)]
            fn deref_mut(&mut self) -> &mut Self::Target {
                &mut self.0
            }
        }
        impl From<crate::W<BUFFER_SPEC>> for W {
            #[inline(always)]
            fn from(writer: crate::W<BUFFER_SPEC>) -> Self {
                W(writer)
            }
        }
        #[doc = "Field `DATA` reader - "]
        pub type DATA_R = crate::FieldReader;
        #[doc = "Field `DATA` writer - "]
        pub type DATA_W<'a, const O: u8> = crate::FieldWriterSafe<'a, BUFFER_SPEC, 8, O>;
        impl R {
            #[doc = "Bits 0:7"]
            #[inline(always)]
            pub fn data(&self) -> DATA_R {
                DATA_R::new((self.bits & 0xff) as u8)
            }
        }
        impl W {
            #[doc = "Bits 0:7"]
            #[inline(always)]
            #[must_use]
            pub fn data(&mut self) -> DATA_W<0> {
                DATA_W::new(self)
            }
            #[doc = "Writes raw bits to the register."]
            #[inline(always)]
            pub unsafe fn bits(&mut self, bits: u32) -> &mut Self {
                self.0.bits(bits);
                self
            }
        }
        #[doc = "\n\nThis register you can [`read`](crate::generic::Reg::read), [`write_with_zero`](crate::generic::Reg::write_with_zero), [`reset`](crate::generic::Reg::reset), [`write`](crate::generic::Reg::write), [`modify`](crate::generic::Reg::modify). See [API](https://docs.rs/svd2rust/#read--modify--write-api).\n\nFor information about available fields see [buffer](index.html) module"]
        pub struct BUFFER_SPEC;
        impl crate::RegisterSpec for BUFFER_SPEC {
            type Ux = u32;
        }
        #[doc = "`read()` method returns [buffer::R](R) reader structure"]
        impl crate::Readable for BUFFER_SPEC {
            type Reader = R;
        }
        #[doc = "`write(|w| ..)` method takes [buffer::W](W) writer structure"]
        impl crate::Writable for BUFFER_SPEC {
            type Writer = W;
            const ZERO_TO_MODIFY_FIELDS_BITMAP: Self::Ux = 0;
            const ONE_TO_MODIFY_FIELDS_BITMAP: Self::Ux = 0;
        }
        #[doc = "`reset()` method sets BUFFER[%s] to value 0"]
        impl crate::Resettable for BUFFER_SPEC {
            const RESET_VALUE: Self::Ux = 0;
        }
    }
    #[doc = "OPERATION_STATUS (rw) register accessor: an alias for `Reg<OPERATION_STATUS_SPEC>`"]
    pub type OPERATION_STATUS = crate::Reg<operation_status::OPERATION_STATUS_SPEC>;
    #[doc = ""]
    pub mod operation_status {
        #[doc = "Register `OPERATION_STATUS` reader"]
        pub struct R(crate::R<OPERATION_STATUS_SPEC>);
        impl core::ops::Deref for R {
            type Target = crate::R<OPERATION_STATUS_SPEC>;
            #[inline(always)]
            fn deref(&self) -> &Self::Target {
                &self.0
            }
        }
        impl From<crate::R<OPERATION_STATUS_SPEC>> for R {
            #[inline(always)]
            fn from(reader: crate::R<OPERATION_STATUS_SPEC>) -> Self {
                R(reader)
            }
        }
        #[doc = "Register `OPERATION_STATUS` writer"]
        pub struct W(crate::W<OPERATION_STATUS_SPEC>);
        impl core::ops::Deref for W {
            type Target = crate::W<OPERATION_STATUS_SPEC>;
            #[inline(always)]
            fn deref(&self) -> &Self::Target {
                &self.0
            }
        }
        impl core::ops::DerefMut for W {
            #[inline(always)]
            fn deref_mut(&mut self) -> &mut Self::Target {
                &mut self.0
            }
        }
        impl From<crate::W<OPERATION_STATUS_SPEC>> for W {
            #[inline(always)]
            fn from(writer: crate::W<OPERATION_STATUS_SPEC>) -> Self {
                W(writer)
            }
        }
        #[doc = "Field `TX_START` reader - "]
        pub type TX_START_R = crate::BitReader<TX_START_A>;
        #[doc = "\n\nValue on reset: 0"]
        #[derive(Clone, Copy, Debug, PartialEq, Eq)]
        pub enum TX_START_A {
            #[doc = "1: `1`"]
            START = 1,
            #[doc = "0: `0`"]
            IDLE = 0,
        }
        impl From<TX_START_A> for bool {
            #[inline(always)]
            fn from(variant: TX_START_A) -> Self {
                variant as u8 != 0
            }
        }
        impl TX_START_R {
            #[doc = "Get enumerated values variant"]
            #[inline(always)]
            pub fn variant(&self) -> TX_START_A {
                match self.bits {
                    true => TX_START_A::START,
                    false => TX_START_A::IDLE,
                }
            }
            #[doc = "Checks if the value of the field is `START`"]
            #[inline(always)]
            pub fn is_start(&self) -> bool {
                *self == TX_START_A::START
            }
            #[doc = "Checks if the value of the field is `IDLE`"]
            #[inline(always)]
            pub fn is_idle(&self) -> bool {
                *self == TX_START_A::IDLE
            }
        }
        #[doc = "Field `TX_START` writer - "]
        pub type TX_START_W<'a, const O: u8> =
            crate::BitWriter<'a, OPERATION_STATUS_SPEC, O, TX_START_A>;
        impl<'a, const O: u8> TX_START_W<'a, O> {
            #[doc = "`1`"]
            #[inline(always)]
            pub fn start(self) -> &'a mut W {
                self.variant(TX_START_A::START)
            }
            #[doc = "`0`"]
            #[inline(always)]
            pub fn idle(self) -> &'a mut W {
                self.variant(TX_START_A::IDLE)
            }
        }
        #[doc = "Field `TX_RUNNING` reader - "]
        pub type TX_RUNNING_R = crate::BitReader<TX_RUNNING_A>;
        #[doc = "\n\nValue on reset: 0"]
        #[derive(Clone, Copy, Debug, PartialEq, Eq)]
        pub enum TX_RUNNING_A {
            #[doc = "1: `1`"]
            RUNNING = 1,
            #[doc = "0: `0`"]
            IDLE = 0,
        }
        impl From<TX_RUNNING_A> for bool {
            #[inline(always)]
            fn from(variant: TX_RUNNING_A) -> Self {
                variant as u8 != 0
            }
        }
        impl TX_RUNNING_R {
            #[doc = "Get enumerated values variant"]
            #[inline(always)]
            pub fn variant(&self) -> TX_RUNNING_A {
                match self.bits {
                    true => TX_RUNNING_A::RUNNING,
                    false => TX_RUNNING_A::IDLE,
                }
            }
            #[doc = "Checks if the value of the field is `RUNNING`"]
            #[inline(always)]
            pub fn is_running(&self) -> bool {
                *self == TX_RUNNING_A::RUNNING
            }
            #[doc = "Checks if the value of the field is `IDLE`"]
            #[inline(always)]
            pub fn is_idle(&self) -> bool {
                *self == TX_RUNNING_A::IDLE
            }
        }
        #[doc = "Field `RX_ENABLE` reader - "]
        pub type RX_ENABLE_R = crate::BitReader<RX_ENABLE_A>;
        #[doc = "\n\nValue on reset: 0"]
        #[derive(Clone, Copy, Debug, PartialEq, Eq)]
        pub enum RX_ENABLE_A {
            #[doc = "1: `1`"]
            ENABLED = 1,
            #[doc = "0: `0`"]
            DISABLED = 0,
        }
        impl From<RX_ENABLE_A> for bool {
            #[inline(always)]
            fn from(variant: RX_ENABLE_A) -> Self {
                variant as u8 != 0
            }
        }
        impl RX_ENABLE_R {
            #[doc = "Get enumerated values variant"]
            #[inline(always)]
            pub fn variant(&self) -> RX_ENABLE_A {
                match self.bits {
                    true => RX_ENABLE_A::ENABLED,
                    false => RX_ENABLE_A::DISABLED,
                }
            }
            #[doc = "Checks if the value of the field is `ENABLED`"]
            #[inline(always)]
            pub fn is_enabled(&self) -> bool {
                *self == RX_ENABLE_A::ENABLED
            }
            #[doc = "Checks if the value of the field is `DISABLED`"]
            #[inline(always)]
            pub fn is_disabled(&self) -> bool {
                *self == RX_ENABLE_A::DISABLED
            }
        }
        #[doc = "Field `RX_ENABLE` writer - "]
        pub type RX_ENABLE_W<'a, const O: u8> =
            crate::BitWriter<'a, OPERATION_STATUS_SPEC, O, RX_ENABLE_A>;
        impl<'a, const O: u8> RX_ENABLE_W<'a, O> {
            #[doc = "`1`"]
            #[inline(always)]
            pub fn enabled(self) -> &'a mut W {
                self.variant(RX_ENABLE_A::ENABLED)
            }
            #[doc = "`0`"]
            #[inline(always)]
            pub fn disabled(self) -> &'a mut W {
                self.variant(RX_ENABLE_A::DISABLED)
            }
        }
        #[doc = "Field `RX_RUNNING` reader - "]
        pub type RX_RUNNING_R = crate::BitReader<RX_RUNNING_A>;
        #[doc = "\n\nValue on reset: 0"]
        #[derive(Clone, Copy, Debug, PartialEq, Eq)]
        pub enum RX_RUNNING_A {
            #[doc = "1: `1`"]
            RUNNING = 1,
            #[doc = "0: `0`"]
            IDLE = 0,
        }
        impl From<RX_RUNNING_A> for bool {
            #[inline(always)]
            fn from(variant: RX_RUNNING_A) -> Self {
                variant as u8 != 0
            }
        }
        impl RX_RUNNING_R {
            #[doc = "Get enumerated values variant"]
            #[inline(always)]
            pub fn variant(&self) -> RX_RUNNING_A {
                match self.bits {
                    true => RX_RUNNING_A::RUNNING,
                    false => RX_RUNNING_A::IDLE,
                }
            }
            #[doc = "Checks if the value of the field is `RUNNING`"]
            #[inline(always)]
            pub fn is_running(&self) -> bool {
                *self == RX_RUNNING_A::RUNNING
            }
            #[doc = "Checks if the value of the field is `IDLE`"]
            #[inline(always)]
            pub fn is_idle(&self) -> bool {
                *self == RX_RUNNING_A::IDLE
            }
        }
        impl R {
            #[doc = "Bit 0"]
            #[inline(always)]
            pub fn tx_start(&self) -> TX_START_R {
                TX_START_R::new((self.bits & 1) != 0)
            }
            #[doc = "Bit 1"]
            #[inline(always)]
            pub fn tx_running(&self) -> TX_RUNNING_R {
                TX_RUNNING_R::new(((self.bits >> 1) & 1) != 0)
            }
            #[doc = "Bit 2"]
            #[inline(always)]
            pub fn rx_enable(&self) -> RX_ENABLE_R {
                RX_ENABLE_R::new(((self.bits >> 2) & 1) != 0)
            }
            #[doc = "Bit 3"]
            #[inline(always)]
            pub fn rx_running(&self) -> RX_RUNNING_R {
                RX_RUNNING_R::new(((self.bits >> 3) & 1) != 0)
            }
        }
        impl W {
            #[doc = "Bit 0"]
            #[inline(always)]
            #[must_use]
            pub fn tx_start(&mut self) -> TX_START_W<0> {
                TX_START_W::new(self)
            }
            #[doc = "Bit 2"]
            #[inline(always)]
            #[must_use]
            pub fn rx_enable(&mut self) -> RX_ENABLE_W<2> {
                RX_ENABLE_W::new(self)
            }
            #[doc = "Writes raw bits to the register."]
            #[inline(always)]
            pub unsafe fn bits(&mut self, bits: u32) -> &mut Self {
                self.0.bits(bits);
                self
            }
        }
        #[doc = "\n\nThis register you can [`read`](crate::generic::Reg::read), [`write_with_zero`](crate::generic::Reg::write_with_zero), [`reset`](crate::generic::Reg::reset), [`write`](crate::generic::Reg::write), [`modify`](crate::generic::Reg::modify). See [API](https://docs.rs/svd2rust/#read--modify--write-api).\n\nFor information about available fields see [operation_status](index.html) module"]
        pub struct OPERATION_STATUS_SPEC;
        impl crate::RegisterSpec for OPERATION_STATUS_SPEC {
            type Ux = u32;
        }
        #[doc = "`read()` method returns [operation_status::R](R) reader structure"]
        impl crate::Readable for OPERATION_STATUS_SPEC {
            type Reader = R;
        }
        #[doc = "`write(|w| ..)` method takes [operation_status::W](W) writer structure"]
        impl crate::Writable for OPERATION_STATUS_SPEC {
            type Writer = W;
            const ZERO_TO_MODIFY_FIELDS_BITMAP: Self::Ux = 0;
            const ONE_TO_MODIFY_FIELDS_BITMAP: Self::Ux = 0;
        }
        #[doc = "`reset()` method sets OPERATION_STATUS to value 0"]
        impl crate::Resettable for OPERATION_STATUS_SPEC {
            const RESET_VALUE: Self::Ux = 0;
        }
    }
    #[doc = "INTERRUPT_STATUS (rw) register accessor: an alias for `Reg<INTERRUPT_STATUS_SPEC>`"]
    pub type INTERRUPT_STATUS = crate::Reg<interrupt_status::INTERRUPT_STATUS_SPEC>;
    #[doc = ""]
    pub mod interrupt_status {
        #[doc = "Register `INTERRUPT_STATUS` reader"]
        pub struct R(crate::R<INTERRUPT_STATUS_SPEC>);
        impl core::ops::Deref for R {
            type Target = crate::R<INTERRUPT_STATUS_SPEC>;
            #[inline(always)]
            fn deref(&self) -> &Self::Target {
                &self.0
            }
        }
        impl From<crate::R<INTERRUPT_STATUS_SPEC>> for R {
            #[inline(always)]
            fn from(reader: crate::R<INTERRUPT_STATUS_SPEC>) -> Self {
                R(reader)
            }
        }
        #[doc = "Register `INTERRUPT_STATUS` writer"]
        pub struct W(crate::W<INTERRUPT_STATUS_SPEC>);
        impl core::ops::Deref for W {
            type Target = crate::W<INTERRUPT_STATUS_SPEC>;
            #[inline(always)]
            fn deref(&self) -> &Self::Target {
                &self.0
            }
        }
        impl core::ops::DerefMut for W {
            #[inline(always)]
            fn deref_mut(&mut self) -> &mut Self::Target {
                &mut self.0
            }
        }
        impl From<crate::W<INTERRUPT_STATUS_SPEC>> for W {
            #[inline(always)]
            fn from(writer: crate::W<INTERRUPT_STATUS_SPEC>) -> Self {
                W(writer)
            }
        }
        #[doc = "Field `TX_COMPLETE` reader - "]
        pub type TX_COMPLETE_R = crate::BitReader<TX_COMPLETE_A>;
        #[doc = "\n\nValue on reset: 0"]
        #[derive(Clone, Copy, Debug, PartialEq, Eq)]
        pub enum TX_COMPLETE_A {
            #[doc = "1: `1`"]
            PENDING = 1,
            #[doc = "0: `0`"]
            FREE = 0,
        }
        impl From<TX_COMPLETE_A> for bool {
            #[inline(always)]
            fn from(variant: TX_COMPLETE_A) -> Self {
                variant as u8 != 0
            }
        }
        impl TX_COMPLETE_R {
            #[doc = "Get enumerated values variant"]
            #[inline(always)]
            pub fn variant(&self) -> TX_COMPLETE_A {
                match self.bits {
                    true => TX_COMPLETE_A::PENDING,
                    false => TX_COMPLETE_A::FREE,
                }
            }
            #[doc = "Checks if the value of the field is `PENDING`"]
            #[inline(always)]
            pub fn is_pending(&self) -> bool {
                *self == TX_COMPLETE_A::PENDING
            }
            #[doc = "Checks if the value of the field is `FREE`"]
            #[inline(always)]
            pub fn is_free(&self) -> bool {
                *self == TX_COMPLETE_A::FREE
            }
        }
        #[doc = "Field `TX_COMPLETE` writer - "]
        pub type TX_COMPLETE_W<'a, const O: u8> =
            crate::BitWriter<'a, INTERRUPT_STATUS_SPEC, O, TX_COMPLETE_A>;
        impl<'a, const O: u8> TX_COMPLETE_W<'a, O> {
            #[doc = "`1`"]
            #[inline(always)]
            pub fn pending(self) -> &'a mut W {
                self.variant(TX_COMPLETE_A::PENDING)
            }
            #[doc = "`0`"]
            #[inline(always)]
            pub fn free(self) -> &'a mut W {
                self.variant(TX_COMPLETE_A::FREE)
            }
        }
        #[doc = "Field `RX_COMPLETE` reader - "]
        pub type RX_COMPLETE_R = crate::BitReader<RX_COMPLETE_A>;
        #[doc = "\n\nValue on reset: 0"]
        #[derive(Clone, Copy, Debug, PartialEq, Eq)]
        pub enum RX_COMPLETE_A {
            #[doc = "1: `1`"]
            PENDING = 1,
            #[doc = "0: `0`"]
            FREE = 0,
        }
        impl From<RX_COMPLETE_A> for bool {
            #[inline(always)]
            fn from(variant: RX_COMPLETE_A) -> Self {
                variant as u8 != 0
            }
        }
        impl RX_COMPLETE_R {
            #[doc = "Get enumerated values variant"]
            #[inline(always)]
            pub fn variant(&self) -> RX_COMPLETE_A {
                match self.bits {
                    true => RX_COMPLETE_A::PENDING,
                    false => RX_COMPLETE_A::FREE,
                }
            }
            #[doc = "Checks if the value of the field is `PENDING`"]
            #[inline(always)]
            pub fn is_pending(&self) -> bool {
                *self == RX_COMPLETE_A::PENDING
            }
            #[doc = "Checks if the value of the field is `FREE`"]
            #[inline(always)]
            pub fn is_free(&self) -> bool {
                *self == RX_COMPLETE_A::FREE
            }
        }
        #[doc = "Field `RX_COMPLETE` writer - "]
        pub type RX_COMPLETE_W<'a, const O: u8> =
            crate::BitWriter<'a, INTERRUPT_STATUS_SPEC, O, RX_COMPLETE_A>;
        impl<'a, const O: u8> RX_COMPLETE_W<'a, O> {
            #[doc = "`1`"]
            #[inline(always)]
            pub fn pending(self) -> &'a mut W {
                self.variant(RX_COMPLETE_A::PENDING)
            }
            #[doc = "`0`"]
            #[inline(always)]
            pub fn free(self) -> &'a mut W {
                self.variant(RX_COMPLETE_A::FREE)
            }
        }
        impl R {
            #[doc = "Bit 0"]
            #[inline(always)]
            pub fn tx_complete(&self) -> TX_COMPLETE_R {
                TX_COMPLETE_R::new((self.bits & 1) != 0)
            }
            #[doc = "Bit 1"]
            #[inline(always)]
            pub fn rx_complete(&self) -> RX_COMPLETE_R {
                RX_COMPLETE_R::new(((self.bits >> 1) & 1) != 0)
            }
        }
        impl W {
            #[doc = "Bit 0"]
            #[inline(always)]
            #[must_use]
            pub fn tx_complete(&mut self) -> TX_COMPLETE_W<0> {
                TX_COMPLETE_W::new(self)
            }
            #[doc = "Bit 1"]
            #[inline(always)]
            #[must_use]
            pub fn rx_complete(&mut self) -> RX_COMPLETE_W<1> {
                RX_COMPLETE_W::new(self)
            }
            #[doc = "Writes raw bits to the register."]
            #[inline(always)]
            pub unsafe fn bits(&mut self, bits: u32) -> &mut Self {
                self.0.bits(bits);
                self
            }
        }
        #[doc = "\n\nThis register you can [`read`](crate::generic::Reg::read), [`write_with_zero`](crate::generic::Reg::write_with_zero), [`reset`](crate::generic::Reg::reset), [`write`](crate::generic::Reg::write), [`modify`](crate::generic::Reg::modify). See [API](https://docs.rs/svd2rust/#read--modify--write-api).\n\nFor information about available fields see [interrupt_status](index.html) module"]
        pub struct INTERRUPT_STATUS_SPEC;
        impl crate::RegisterSpec for INTERRUPT_STATUS_SPEC {
            type Ux = u32;
        }
        #[doc = "`read()` method returns [interrupt_status::R](R) reader structure"]
        impl crate::Readable for INTERRUPT_STATUS_SPEC {
            type Reader = R;
        }
        #[doc = "`write(|w| ..)` method takes [interrupt_status::W](W) writer structure"]
        impl crate::Writable for INTERRUPT_STATUS_SPEC {
            type Writer = W;
            const ZERO_TO_MODIFY_FIELDS_BITMAP: Self::Ux = 0;
            const ONE_TO_MODIFY_FIELDS_BITMAP: Self::Ux = 0;
        }
        #[doc = "`reset()` method sets INTERRUPT_STATUS to value 0"]
        impl crate::Resettable for INTERRUPT_STATUS_SPEC {
            const RESET_VALUE: Self::Ux = 0;
        }
    }
    #[doc = "RX_COUNT (rw) register accessor: an alias for `Reg<RX_COUNT_SPEC>`"]
    pub type RX_COUNT = crate::Reg<rx_count::RX_COUNT_SPEC>;
    #[doc = ""]
    pub mod rx_count {
        #[doc = "Register `RX_COUNT` reader"]
        pub struct R(crate::R<RX_COUNT_SPEC>);
        impl core::ops::Deref for R {
            type Target = crate::R<RX_COUNT_SPEC>;
            #[inline(always)]
            fn deref(&self) -> &Self::Target {
                &self.0
            }
        }
        impl From<crate::R<RX_COUNT_SPEC>> for R {
            #[inline(always)]
            fn from(reader: crate::R<RX_COUNT_SPEC>) -> Self {
                R(reader)
            }
        }
        #[doc = "Register `RX_COUNT` writer"]
        pub struct W(crate::W<RX_COUNT_SPEC>);
        impl core::ops::Deref for W {
            type Target = crate::W<RX_COUNT_SPEC>;
            #[inline(always)]
            fn deref(&self) -> &Self::Target {
                &self.0
            }
        }
        impl core::ops::DerefMut for W {
            #[inline(always)]
            fn deref_mut(&mut self) -> &mut Self::Target {
                &mut self.0
            }
        }
        impl From<crate::W<RX_COUNT_SPEC>> for W {
            #[inline(always)]
            fn from(writer: crate::W<RX_COUNT_SPEC>) -> Self {
                W(writer)
            }
        }
        #[doc = "Field `VALUE` reader - "]
        pub type VALUE_R = crate::FieldReader;
        impl R {
            #[doc = "Bits 0:7"]
            #[inline(always)]
            pub fn value(&self) -> VALUE_R {
                VALUE_R::new((self.bits & 0xff) as u8)
            }
        }
        impl W {
            #[doc = "Writes raw bits to the register."]
            #[inline(always)]
            pub unsafe fn bits(&mut self, bits: u32) -> &mut Self {
                self.0.bits(bits);
                self
            }
        }
        #[doc = "\n\nThis register you can [`read`](crate::generic::Reg::read), [`write_with_zero`](crate::generic::Reg::write_with_zero), [`reset`](crate::generic::Reg::reset), [`write`](crate::generic::Reg::write), [`modify`](crate::generic::Reg::modify). See [API](https://docs.rs/svd2rust/#read--modify--write-api).\n\nFor information about available fields see [rx_count](index.html) module"]
        pub struct RX_COUNT_SPEC;
        impl crate::RegisterSpec for RX_COUNT_SPEC {
            type Ux = u32;
        }
        #[doc = "`read()` method returns [rx_count::R](R) reader structure"]
        impl crate::Readable for RX_COUNT_SPEC {
            type Reader = R;
        }
        #[doc = "`write(|w| ..)` method takes [rx_count::W](W) writer structure"]
        impl crate::Writable for RX_COUNT_SPEC {
            type Writer = W;
            const ZERO_TO_MODIFY_FIELDS_BITMAP: Self::Ux = 0;
            const ONE_TO_MODIFY_FIELDS_BITMAP: Self::Ux = 0;
        }
        #[doc = "`reset()` method sets RX_COUNT to value 0"]
        impl crate::Resettable for RX_COUNT_SPEC {
            const RESET_VALUE: Self::Ux = 0;
        }
    }
    #[doc = "RX_INDEX (rw) register accessor: an alias for `Reg<RX_INDEX_SPEC>`"]
    pub type RX_INDEX = crate::Reg<rx_index::RX_INDEX_SPEC>;
    #[doc = ""]
    pub mod rx_index {
        #[doc = "Register `RX_INDEX` reader"]
        pub struct R(crate::R<RX_INDEX_SPEC>);
        impl core::ops::Deref for R {
            type Target = crate::R<RX_INDEX_SPEC>;
            #[inline(always)]
            fn deref(&self) -> &Self::Target {
                &self.0
            }
        }
        impl From<crate::R<RX_INDEX_SPEC>> for R {
            #[inline(always)]
            fn from(reader: crate::R<RX_INDEX_SPEC>) -> Self {
                R(reader)
            }
        }
        #[doc = "Register `RX_INDEX` writer"]
        pub struct W(crate::W<RX_INDEX_SPEC>);
        impl core::ops::Deref for W {
            type Target = crate::W<RX_INDEX_SPEC>;
            #[inline(always)]
            fn deref(&self) -> &Self::Target {
                &self.0
            }
        }
        impl core::ops::DerefMut for W {
            #[inline(always)]
            fn deref_mut(&mut self) -> &mut Self::Target {
                &mut self.0
            }
        }
        impl From<crate::W<RX_INDEX_SPEC>> for W {
            #[inline(always)]
            fn from(writer: crate::W<RX_INDEX_SPEC>) -> Self {
                W(writer)
            }
        }
        #[doc = "Field `VALUE` reader - "]
        pub type VALUE_R = crate::FieldReader;
        #[doc = "Field `VALUE` writer - "]
        pub type VALUE_W<'a, const O: u8> = crate::FieldWriterSafe<'a, RX_INDEX_SPEC, 8, O>;
        impl R {
            #[doc = "Bits 0:7"]
            #[inline(always)]
            pub fn value(&self) -> VALUE_R {
                VALUE_R::new((self.bits & 0xff) as u8)
            }
        }
        impl W {
            #[doc = "Bits 0:7"]
            #[inline(always)]
            #[must_use]
            pub fn value(&mut self) -> VALUE_W<0> {
                VALUE_W::new(self)
            }
            #[doc = "Writes raw bits to the register."]
            #[inline(always)]
            pub unsafe fn bits(&mut self, bits: u32) -> &mut Self {
                self.0.bits(bits);
                self
            }
        }
        #[doc = "\n\nThis register you can [`read`](crate::generic::Reg::read), [`write_with_zero`](crate::generic::Reg::write_with_zero), [`reset`](crate::generic::Reg::reset), [`write`](crate::generic::Reg::write), [`modify`](crate::generic::Reg::modify). See [API](https://docs.rs/svd2rust/#read--modify--write-api).\n\nFor information about available fields see [rx_index](index.html) module"]
        pub struct RX_INDEX_SPEC;
        impl crate::RegisterSpec for RX_INDEX_SPEC {
            type Ux = u32;
        }
        #[doc = "`read()` method returns [rx_index::R](R) reader structure"]
        impl crate::Readable for RX_INDEX_SPEC {
            type Reader = R;
        }
        #[doc = "`write(|w| ..)` method takes [rx_index::W](W) writer structure"]
        impl crate::Writable for RX_INDEX_SPEC {
            type Writer = W;
            const ZERO_TO_MODIFY_FIELDS_BITMAP: Self::Ux = 0;
            const ONE_TO_MODIFY_FIELDS_BITMAP: Self::Ux = 0;
        }
        #[doc = "`reset()` method sets RX_INDEX to value 0"]
        impl crate::Resettable for RX_INDEX_SPEC {
            const RESET_VALUE: Self::Ux = 0;
        }
    }
    #[doc = "TX_COUNT (rw) register accessor: an alias for `Reg<TX_COUNT_SPEC>`"]
    pub type TX_COUNT = crate::Reg<tx_count::TX_COUNT_SPEC>;
    #[doc = ""]
    pub mod tx_count {
        #[doc = "Register `TX_COUNT` reader"]
        pub struct R(crate::R<TX_COUNT_SPEC>);
        impl core::ops::Deref for R {
            type Target = crate::R<TX_COUNT_SPEC>;
            #[inline(always)]
            fn deref(&self) -> &Self::Target {
                &self.0
            }
        }
        impl From<crate::R<TX_COUNT_SPEC>> for R {
            #[inline(always)]
            fn from(reader: crate::R<TX_COUNT_SPEC>) -> Self {
                R(reader)
            }
        }
        #[doc = "Register `TX_COUNT` writer"]
        pub struct W(crate::W<TX_COUNT_SPEC>);
        impl core::ops::Deref for W {
            type Target = crate::W<TX_COUNT_SPEC>;
            #[inline(always)]
            fn deref(&self) -> &Self::Target {
                &self.0
            }
        }
        impl core::ops::DerefMut for W {
            #[inline(always)]
            fn deref_mut(&mut self) -> &mut Self::Target {
                &mut self.0
            }
        }
        impl From<crate::W<TX_COUNT_SPEC>> for W {
            #[inline(always)]
            fn from(writer: crate::W<TX_COUNT_SPEC>) -> Self {
                W(writer)
            }
        }
        #[doc = "Field `VALUE` reader - "]
        pub type VALUE_R = crate::FieldReader;
        #[doc = "Field `VALUE` writer - "]
        pub type VALUE_W<'a, const O: u8> = crate::FieldWriterSafe<'a, TX_COUNT_SPEC, 8, O>;
        impl R {
            #[doc = "Bits 0:7"]
            #[inline(always)]
            pub fn value(&self) -> VALUE_R {
                VALUE_R::new((self.bits & 0xff) as u8)
            }
        }
        impl W {
            #[doc = "Bits 0:7"]
            #[inline(always)]
            #[must_use]
            pub fn value(&mut self) -> VALUE_W<0> {
                VALUE_W::new(self)
            }
            #[doc = "Writes raw bits to the register."]
            #[inline(always)]
            pub unsafe fn bits(&mut self, bits: u32) -> &mut Self {
                self.0.bits(bits);
                self
            }
        }
        #[doc = "\n\nThis register you can [`read`](crate::generic::Reg::read), [`write_with_zero`](crate::generic::Reg::write_with_zero), [`reset`](crate::generic::Reg::reset), [`write`](crate::generic::Reg::write), [`modify`](crate::generic::Reg::modify). See [API](https://docs.rs/svd2rust/#read--modify--write-api).\n\nFor information about available fields see [tx_count](index.html) module"]
        pub struct TX_COUNT_SPEC;
        impl crate::RegisterSpec for TX_COUNT_SPEC {
            type Ux = u32;
        }
        #[doc = "`read()` method returns [tx_count::R](R) reader structure"]
        impl crate::Readable for TX_COUNT_SPEC {
            type Reader = R;
        }
        #[doc = "`write(|w| ..)` method takes [tx_count::W](W) writer structure"]
        impl crate::Writable for TX_COUNT_SPEC {
            type Writer = W;
            const ZERO_TO_MODIFY_FIELDS_BITMAP: Self::Ux = 0;
            const ONE_TO_MODIFY_FIELDS_BITMAP: Self::Ux = 0;
        }
        #[doc = "`reset()` method sets TX_COUNT to value 0"]
        impl crate::Resettable for TX_COUNT_SPEC {
            const RESET_VALUE: Self::Ux = 0;
        }
    }
    #[doc = "TX_INDEX (rw) register accessor: an alias for `Reg<TX_INDEX_SPEC>`"]
    pub type TX_INDEX = crate::Reg<tx_index::TX_INDEX_SPEC>;
    #[doc = ""]
    pub mod tx_index {
        #[doc = "Register `TX_INDEX` reader"]
        pub struct R(crate::R<TX_INDEX_SPEC>);
        impl core::ops::Deref for R {
            type Target = crate::R<TX_INDEX_SPEC>;
            #[inline(always)]
            fn deref(&self) -> &Self::Target {
                &self.0
            }
        }
        impl From<crate::R<TX_INDEX_SPEC>> for R {
            #[inline(always)]
            fn from(reader: crate::R<TX_INDEX_SPEC>) -> Self {
                R(reader)
            }
        }
        #[doc = "Register `TX_INDEX` writer"]
        pub struct W(crate::W<TX_INDEX_SPEC>);
        impl core::ops::Deref for W {
            type Target = crate::W<TX_INDEX_SPEC>;
            #[inline(always)]
            fn deref(&self) -> &Self::Target {
                &self.0
            }
        }
        impl core::ops::DerefMut for W {
            #[inline(always)]
            fn deref_mut(&mut self) -> &mut Self::Target {
                &mut self.0
            }
        }
        impl From<crate::W<TX_INDEX_SPEC>> for W {
            #[inline(always)]
            fn from(writer: crate::W<TX_INDEX_SPEC>) -> Self {
                W(writer)
            }
        }
        #[doc = "Field `VALUE` reader - "]
        pub type VALUE_R = crate::FieldReader;
        #[doc = "Field `VALUE` writer - "]
        pub type VALUE_W<'a, const O: u8> = crate::FieldWriterSafe<'a, TX_INDEX_SPEC, 8, O>;
        impl R {
            #[doc = "Bits 0:7"]
            #[inline(always)]
            pub fn value(&self) -> VALUE_R {
                VALUE_R::new((self.bits & 0xff) as u8)
            }
        }
        impl W {
            #[doc = "Bits 0:7"]
            #[inline(always)]
            #[must_use]
            pub fn value(&mut self) -> VALUE_W<0> {
                VALUE_W::new(self)
            }
            #[doc = "Writes raw bits to the register."]
            #[inline(always)]
            pub unsafe fn bits(&mut self, bits: u32) -> &mut Self {
                self.0.bits(bits);
                self
            }
        }
        #[doc = "\n\nThis register you can [`read`](crate::generic::Reg::read), [`write_with_zero`](crate::generic::Reg::write_with_zero), [`reset`](crate::generic::Reg::reset), [`write`](crate::generic::Reg::write), [`modify`](crate::generic::Reg::modify). See [API](https://docs.rs/svd2rust/#read--modify--write-api).\n\nFor information about available fields see [tx_index](index.html) module"]
        pub struct TX_INDEX_SPEC;
        impl crate::RegisterSpec for TX_INDEX_SPEC {
            type Ux = u32;
        }
        #[doc = "`read()` method returns [tx_index::R](R) reader structure"]
        impl crate::Readable for TX_INDEX_SPEC {
            type Reader = R;
        }
        #[doc = "`write(|w| ..)` method takes [tx_index::W](W) writer structure"]
        impl crate::Writable for TX_INDEX_SPEC {
            type Writer = W;
            const ZERO_TO_MODIFY_FIELDS_BITMAP: Self::Ux = 0;
            const ONE_TO_MODIFY_FIELDS_BITMAP: Self::Ux = 0;
        }
        #[doc = "`reset()` method sets TX_INDEX to value 0"]
        impl crate::Resettable for TX_INDEX_SPEC {
            const RESET_VALUE: Self::Ux = 0;
        }
    }
}
#[doc = "DisplayPort main-link control (Phase C)"]
pub struct MAIN_LINK {
    _marker: PhantomData<*const ()>,
}
unsafe impl Send for MAIN_LINK {}
impl MAIN_LINK {
    #[doc = r"Pointer to the register block"]
    pub const PTR: *const main_link::RegisterBlock = 0x4002_0000 as *const _;
    #[doc = r"Return the pointer to the register block"]
    #[inline(always)]
    pub const fn ptr() -> *const main_link::RegisterBlock {
        Self::PTR
    }
}
impl Deref for MAIN_LINK {
    type Target = main_link::RegisterBlock;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        unsafe { &*Self::PTR }
    }
}
impl core::fmt::Debug for MAIN_LINK {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("MAIN_LINK").finish()
    }
}
#[doc = "DisplayPort main-link control (Phase C)"]
pub mod main_link {
    #[doc = r"Register block"]
    #[repr(C)]
    pub struct RegisterBlock {
        #[doc = "0x00 - Main-link control. Pattern select / enable / RD reset pulse."]
        pub ctrl: CTRL,
        #[doc = "0x04 - Active lane count (1, 2, or 4). Phase C uses 1 only."]
        pub lane_count: LANE_COUNT,
        #[doc = "0x08 - Drive setting for lane 0 (informational in sim)."]
        pub lane0_drive: LANE0_DRIVE,
    }
    #[doc = "CTRL (rw) register accessor: an alias for `Reg<CTRL_SPEC>`"]
    pub type CTRL = crate::Reg<ctrl::CTRL_SPEC>;
    #[doc = "Main-link control. Pattern select / enable / RD reset pulse."]
    pub mod ctrl {
        #[doc = "Register `CTRL` reader"]
        pub struct R(crate::R<CTRL_SPEC>);
        impl core::ops::Deref for R {
            type Target = crate::R<CTRL_SPEC>;
            #[inline(always)]
            fn deref(&self) -> &Self::Target {
                &self.0
            }
        }
        impl From<crate::R<CTRL_SPEC>> for R {
            #[inline(always)]
            fn from(reader: crate::R<CTRL_SPEC>) -> Self {
                R(reader)
            }
        }
        #[doc = "Register `CTRL` writer"]
        pub struct W(crate::W<CTRL_SPEC>);
        impl core::ops::Deref for W {
            type Target = crate::W<CTRL_SPEC>;
            #[inline(always)]
            fn deref(&self) -> &Self::Target {
                &self.0
            }
        }
        impl core::ops::DerefMut for W {
            #[inline(always)]
            fn deref_mut(&mut self) -> &mut Self::Target {
                &mut self.0
            }
        }
        impl From<crate::W<CTRL_SPEC>> for W {
            #[inline(always)]
            fn from(writer: crate::W<CTRL_SPEC>) -> Self {
                W(writer)
            }
        }
        #[doc = "Field `PATTERN_SELECT` reader - 00=IDLE, 01=TPS1, 10=TPS2 (DP 1.2 Tab 3-16)"]
        pub type PATTERN_SELECT_R = crate::FieldReader;
        #[doc = "Field `PATTERN_SELECT` writer - 00=IDLE, 01=TPS1, 10=TPS2 (DP 1.2 Tab 3-16)"]
        pub type PATTERN_SELECT_W<'a, const O: u8> = crate::FieldWriter<'a, CTRL_SPEC, 2, O>;
        #[doc = "Field `ENABLE` reader - 1 = main link transmitter enabled"]
        pub type ENABLE_R = crate::BitReader;
        #[doc = "Field `ENABLE` writer - 1 = main link transmitter enabled"]
        pub type ENABLE_W<'a, const O: u8> = crate::BitWriter<'a, CTRL_SPEC, O>;
        #[doc = "Field `RD_RESET` reader - Write 1 to force the next encoder input to start at RD=- (DP 1.2 §3.5.1.2). Self-clearing."]
        pub type RD_RESET_R = crate::BitReader;
        #[doc = "Field `RD_RESET` writer - Write 1 to force the next encoder input to start at RD=- (DP 1.2 §3.5.1.2). Self-clearing."]
        pub type RD_RESET_W<'a, const O: u8> = crate::BitWriter<'a, CTRL_SPEC, O>;
        impl R {
            #[doc = "Bits 0:1 - 00=IDLE, 01=TPS1, 10=TPS2 (DP 1.2 Tab 3-16)"]
            #[inline(always)]
            pub fn pattern_select(&self) -> PATTERN_SELECT_R {
                PATTERN_SELECT_R::new((self.bits & 3) as u8)
            }
            #[doc = "Bit 4 - 1 = main link transmitter enabled"]
            #[inline(always)]
            pub fn enable(&self) -> ENABLE_R {
                ENABLE_R::new(((self.bits >> 4) & 1) != 0)
            }
            #[doc = "Bit 5 - Write 1 to force the next encoder input to start at RD=- (DP 1.2 §3.5.1.2). Self-clearing."]
            #[inline(always)]
            pub fn rd_reset(&self) -> RD_RESET_R {
                RD_RESET_R::new(((self.bits >> 5) & 1) != 0)
            }
        }
        impl W {
            #[doc = "Bits 0:1 - 00=IDLE, 01=TPS1, 10=TPS2 (DP 1.2 Tab 3-16)"]
            #[inline(always)]
            #[must_use]
            pub fn pattern_select(&mut self) -> PATTERN_SELECT_W<0> {
                PATTERN_SELECT_W::new(self)
            }
            #[doc = "Bit 4 - 1 = main link transmitter enabled"]
            #[inline(always)]
            #[must_use]
            pub fn enable(&mut self) -> ENABLE_W<4> {
                ENABLE_W::new(self)
            }
            #[doc = "Bit 5 - Write 1 to force the next encoder input to start at RD=- (DP 1.2 §3.5.1.2). Self-clearing."]
            #[inline(always)]
            #[must_use]
            pub fn rd_reset(&mut self) -> RD_RESET_W<5> {
                RD_RESET_W::new(self)
            }
            #[doc = "Writes raw bits to the register."]
            #[inline(always)]
            pub unsafe fn bits(&mut self, bits: u32) -> &mut Self {
                self.0.bits(bits);
                self
            }
        }
        #[doc = "Main-link control. Pattern select / enable / RD reset pulse.\n\nThis register you can [`read`](crate::generic::Reg::read), [`write_with_zero`](crate::generic::Reg::write_with_zero), [`reset`](crate::generic::Reg::reset), [`write`](crate::generic::Reg::write), [`modify`](crate::generic::Reg::modify). See [API](https://docs.rs/svd2rust/#read--modify--write-api).\n\nFor information about available fields see [ctrl](index.html) module"]
        pub struct CTRL_SPEC;
        impl crate::RegisterSpec for CTRL_SPEC {
            type Ux = u32;
        }
        #[doc = "`read()` method returns [ctrl::R](R) reader structure"]
        impl crate::Readable for CTRL_SPEC {
            type Reader = R;
        }
        #[doc = "`write(|w| ..)` method takes [ctrl::W](W) writer structure"]
        impl crate::Writable for CTRL_SPEC {
            type Writer = W;
            const ZERO_TO_MODIFY_FIELDS_BITMAP: Self::Ux = 0;
            const ONE_TO_MODIFY_FIELDS_BITMAP: Self::Ux = 0;
        }
        #[doc = "`reset()` method sets CTRL to value 0"]
        impl crate::Resettable for CTRL_SPEC {
            const RESET_VALUE: Self::Ux = 0;
        }
    }
    #[doc = "LANE_COUNT (rw) register accessor: an alias for `Reg<LANE_COUNT_SPEC>`"]
    pub type LANE_COUNT = crate::Reg<lane_count::LANE_COUNT_SPEC>;
    #[doc = "Active lane count (1, 2, or 4). Phase C uses 1 only."]
    pub mod lane_count {
        #[doc = "Register `LANE_COUNT` reader"]
        pub struct R(crate::R<LANE_COUNT_SPEC>);
        impl core::ops::Deref for R {
            type Target = crate::R<LANE_COUNT_SPEC>;
            #[inline(always)]
            fn deref(&self) -> &Self::Target {
                &self.0
            }
        }
        impl From<crate::R<LANE_COUNT_SPEC>> for R {
            #[inline(always)]
            fn from(reader: crate::R<LANE_COUNT_SPEC>) -> Self {
                R(reader)
            }
        }
        #[doc = "Register `LANE_COUNT` writer"]
        pub struct W(crate::W<LANE_COUNT_SPEC>);
        impl core::ops::Deref for W {
            type Target = crate::W<LANE_COUNT_SPEC>;
            #[inline(always)]
            fn deref(&self) -> &Self::Target {
                &self.0
            }
        }
        impl core::ops::DerefMut for W {
            #[inline(always)]
            fn deref_mut(&mut self) -> &mut Self::Target {
                &mut self.0
            }
        }
        impl From<crate::W<LANE_COUNT_SPEC>> for W {
            #[inline(always)]
            fn from(writer: crate::W<LANE_COUNT_SPEC>) -> Self {
                W(writer)
            }
        }
        #[doc = "Field `VALUE` reader - "]
        pub type VALUE_R = crate::FieldReader;
        #[doc = "Field `VALUE` writer - "]
        pub type VALUE_W<'a, const O: u8> = crate::FieldWriter<'a, LANE_COUNT_SPEC, 3, O>;
        impl R {
            #[doc = "Bits 0:2"]
            #[inline(always)]
            pub fn value(&self) -> VALUE_R {
                VALUE_R::new((self.bits & 7) as u8)
            }
        }
        impl W {
            #[doc = "Bits 0:2"]
            #[inline(always)]
            #[must_use]
            pub fn value(&mut self) -> VALUE_W<0> {
                VALUE_W::new(self)
            }
            #[doc = "Writes raw bits to the register."]
            #[inline(always)]
            pub unsafe fn bits(&mut self, bits: u32) -> &mut Self {
                self.0.bits(bits);
                self
            }
        }
        #[doc = "Active lane count (1, 2, or 4). Phase C uses 1 only.\n\nThis register you can [`read`](crate::generic::Reg::read), [`write_with_zero`](crate::generic::Reg::write_with_zero), [`reset`](crate::generic::Reg::reset), [`write`](crate::generic::Reg::write), [`modify`](crate::generic::Reg::modify). See [API](https://docs.rs/svd2rust/#read--modify--write-api).\n\nFor information about available fields see [lane_count](index.html) module"]
        pub struct LANE_COUNT_SPEC;
        impl crate::RegisterSpec for LANE_COUNT_SPEC {
            type Ux = u32;
        }
        #[doc = "`read()` method returns [lane_count::R](R) reader structure"]
        impl crate::Readable for LANE_COUNT_SPEC {
            type Reader = R;
        }
        #[doc = "`write(|w| ..)` method takes [lane_count::W](W) writer structure"]
        impl crate::Writable for LANE_COUNT_SPEC {
            type Writer = W;
            const ZERO_TO_MODIFY_FIELDS_BITMAP: Self::Ux = 0;
            const ONE_TO_MODIFY_FIELDS_BITMAP: Self::Ux = 0;
        }
        #[doc = "`reset()` method sets LANE_COUNT to value 0"]
        impl crate::Resettable for LANE_COUNT_SPEC {
            const RESET_VALUE: Self::Ux = 0;
        }
    }
    #[doc = "LANE0_DRIVE (rw) register accessor: an alias for `Reg<LANE0_DRIVE_SPEC>`"]
    pub type LANE0_DRIVE = crate::Reg<lane0_drive::LANE0_DRIVE_SPEC>;
    #[doc = "Drive setting for lane 0 (informational in sim)."]
    pub mod lane0_drive {
        #[doc = "Register `LANE0_DRIVE` reader"]
        pub struct R(crate::R<LANE0_DRIVE_SPEC>);
        impl core::ops::Deref for R {
            type Target = crate::R<LANE0_DRIVE_SPEC>;
            #[inline(always)]
            fn deref(&self) -> &Self::Target {
                &self.0
            }
        }
        impl From<crate::R<LANE0_DRIVE_SPEC>> for R {
            #[inline(always)]
            fn from(reader: crate::R<LANE0_DRIVE_SPEC>) -> Self {
                R(reader)
            }
        }
        #[doc = "Register `LANE0_DRIVE` writer"]
        pub struct W(crate::W<LANE0_DRIVE_SPEC>);
        impl core::ops::Deref for W {
            type Target = crate::W<LANE0_DRIVE_SPEC>;
            #[inline(always)]
            fn deref(&self) -> &Self::Target {
                &self.0
            }
        }
        impl core::ops::DerefMut for W {
            #[inline(always)]
            fn deref_mut(&mut self) -> &mut Self::Target {
                &mut self.0
            }
        }
        impl From<crate::W<LANE0_DRIVE_SPEC>> for W {
            #[inline(always)]
            fn from(writer: crate::W<LANE0_DRIVE_SPEC>) -> Self {
                W(writer)
            }
        }
        #[doc = "Field `VOLTAGE_SWING` reader - "]
        pub type VOLTAGE_SWING_R = crate::FieldReader;
        #[doc = "Field `VOLTAGE_SWING` writer - "]
        pub type VOLTAGE_SWING_W<'a, const O: u8> = crate::FieldWriter<'a, LANE0_DRIVE_SPEC, 2, O>;
        #[doc = "Field `MAX_SWING` reader - "]
        pub type MAX_SWING_R = crate::BitReader;
        #[doc = "Field `MAX_SWING` writer - "]
        pub type MAX_SWING_W<'a, const O: u8> = crate::BitWriter<'a, LANE0_DRIVE_SPEC, O>;
        #[doc = "Field `PRE_EMPHASIS` reader - "]
        pub type PRE_EMPHASIS_R = crate::FieldReader;
        #[doc = "Field `PRE_EMPHASIS` writer - "]
        pub type PRE_EMPHASIS_W<'a, const O: u8> = crate::FieldWriter<'a, LANE0_DRIVE_SPEC, 2, O>;
        #[doc = "Field `MAX_PRE_EMPHASIS` reader - "]
        pub type MAX_PRE_EMPHASIS_R = crate::BitReader;
        #[doc = "Field `MAX_PRE_EMPHASIS` writer - "]
        pub type MAX_PRE_EMPHASIS_W<'a, const O: u8> = crate::BitWriter<'a, LANE0_DRIVE_SPEC, O>;
        impl R {
            #[doc = "Bits 0:1"]
            #[inline(always)]
            pub fn voltage_swing(&self) -> VOLTAGE_SWING_R {
                VOLTAGE_SWING_R::new((self.bits & 3) as u8)
            }
            #[doc = "Bit 2"]
            #[inline(always)]
            pub fn max_swing(&self) -> MAX_SWING_R {
                MAX_SWING_R::new(((self.bits >> 2) & 1) != 0)
            }
            #[doc = "Bits 3:4"]
            #[inline(always)]
            pub fn pre_emphasis(&self) -> PRE_EMPHASIS_R {
                PRE_EMPHASIS_R::new(((self.bits >> 3) & 3) as u8)
            }
            #[doc = "Bit 5"]
            #[inline(always)]
            pub fn max_pre_emphasis(&self) -> MAX_PRE_EMPHASIS_R {
                MAX_PRE_EMPHASIS_R::new(((self.bits >> 5) & 1) != 0)
            }
        }
        impl W {
            #[doc = "Bits 0:1"]
            #[inline(always)]
            #[must_use]
            pub fn voltage_swing(&mut self) -> VOLTAGE_SWING_W<0> {
                VOLTAGE_SWING_W::new(self)
            }
            #[doc = "Bit 2"]
            #[inline(always)]
            #[must_use]
            pub fn max_swing(&mut self) -> MAX_SWING_W<2> {
                MAX_SWING_W::new(self)
            }
            #[doc = "Bits 3:4"]
            #[inline(always)]
            #[must_use]
            pub fn pre_emphasis(&mut self) -> PRE_EMPHASIS_W<3> {
                PRE_EMPHASIS_W::new(self)
            }
            #[doc = "Bit 5"]
            #[inline(always)]
            #[must_use]
            pub fn max_pre_emphasis(&mut self) -> MAX_PRE_EMPHASIS_W<5> {
                MAX_PRE_EMPHASIS_W::new(self)
            }
            #[doc = "Writes raw bits to the register."]
            #[inline(always)]
            pub unsafe fn bits(&mut self, bits: u32) -> &mut Self {
                self.0.bits(bits);
                self
            }
        }
        #[doc = "Drive setting for lane 0 (informational in sim).\n\nThis register you can [`read`](crate::generic::Reg::read), [`write_with_zero`](crate::generic::Reg::write_with_zero), [`reset`](crate::generic::Reg::reset), [`write`](crate::generic::Reg::write), [`modify`](crate::generic::Reg::modify). See [API](https://docs.rs/svd2rust/#read--modify--write-api).\n\nFor information about available fields see [lane0_drive](index.html) module"]
        pub struct LANE0_DRIVE_SPEC;
        impl crate::RegisterSpec for LANE0_DRIVE_SPEC {
            type Ux = u32;
        }
        #[doc = "`read()` method returns [lane0_drive::R](R) reader structure"]
        impl crate::Readable for LANE0_DRIVE_SPEC {
            type Reader = R;
        }
        #[doc = "`write(|w| ..)` method takes [lane0_drive::W](W) writer structure"]
        impl crate::Writable for LANE0_DRIVE_SPEC {
            type Writer = W;
            const ZERO_TO_MODIFY_FIELDS_BITMAP: Self::Ux = 0;
            const ONE_TO_MODIFY_FIELDS_BITMAP: Self::Ux = 0;
        }
        #[doc = "`reset()` method sets LANE0_DRIVE to value 0"]
        impl crate::Resettable for LANE0_DRIVE_SPEC {
            const RESET_VALUE: Self::Ux = 0;
        }
    }
}
#[no_mangle]
static mut DEVICE_PERIPHERALS: bool = false;
#[doc = r" All the peripherals."]
#[allow(non_snake_case)]
pub struct Peripherals {
    #[doc = "SYSTEM"]
    pub SYSTEM: SYSTEM,
    #[doc = "SYSTEM_SERIALOUT"]
    pub SYSTEM_SERIALOUT: SYSTEM_SERIALOUT,
    #[doc = "AUX_CH"]
    pub AUX_CH: AUX_CH,
    #[doc = "MAIN_LINK"]
    pub MAIN_LINK: MAIN_LINK,
}
impl Peripherals {
    #[doc = r" Returns all the peripherals *once*."]
    #[cfg(feature = "critical-section")]
    #[inline]
    pub fn take() -> Option<Self> {
        critical_section::with(|_| {
            if unsafe { DEVICE_PERIPHERALS } {
                return None;
            }
            Some(unsafe { Peripherals::steal() })
        })
    }
    #[doc = r" Unchecked version of `Peripherals::take`."]
    #[doc = r""]
    #[doc = r" # Safety"]
    #[doc = r""]
    #[doc = r" Each of the returned peripherals must be used at most once."]
    #[inline]
    pub unsafe fn steal() -> Self {
        DEVICE_PERIPHERALS = true;
        Peripherals {
            SYSTEM: SYSTEM {
                _marker: PhantomData,
            },
            SYSTEM_SERIALOUT: SYSTEM_SERIALOUT {
                _marker: PhantomData,
            },
            AUX_CH: AUX_CH {
                _marker: PhantomData,
            },
            MAIN_LINK: MAIN_LINK {
                _marker: PhantomData,
            },
        }
    }
}
