[project]
name = "display_controller_tangnano9k"
version = "0.1.0"
authors = ["Kenta IDA <fuga@fugafuga.org>"]
license = "BSL-1.0"

[build]
target = { type = "source" }

[dependencies]
spi = {path = "../../../../rtl/spi"}
axi4s = {path = "../../../../rtl/interfaces/axi4s"}
sync = {path = "../../../../rtl/sync"}
display_controller = {path = "../../../../rtl/display_controller"}
